/*
* Created on 26-Apr-2010
*/
package nic.watersoft.masters;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import nic.watersoft.commons.Debug;
import nic.watersoft.commons.RwsOffices;


public class HabConvertDao {
	
	//Deepak Modified
	public ArrayList covertOldHabToNewHab(String habCodeOld,String habCodeNew,String coveredStatus) {
		ArrayList returnList = new ArrayList();
		String[] oldValues = new String[150];
		String statusTracker = "STARTED";
		int[] returnValue = new int[150];
		int iter = -1;
		for(int i=0;i<150;i++)returnValue[i]=0;
		Connection con = null,con1 = null;
		try	{
			con = RwsOffices.getConn();
			con1 = RwsOffices.getConn();
			con.setAutoCommit(false);
			HabConvertDao hd = new HabConvertDao();			
			statusTracker = "";
			boolean b = true;
			String q = "SELECT"
					+ "( SELECT COUNT(*) FROM RWS_HABITATION_DIR_DYNA_TBL WHERE HAB_CODE='"+habCodeNew+"')a, "
					+ "(SELECT COUNT(*) FROM RWS_HABMAST_TBL WHERE PRHAB='"+habCodeNew+"')d,"
					+ "(SELECT COUNT(*) FROM RWS_HABMAST_TBL WHERE SUBSTR(HAB_CODE,1,14)='"+habCodeNew.substring(0,14)+"')e, "
					+ "(SELECT COUNT(*) FROM RWS_HAB_SUPPLY_STATUS_TBL WHERE HAB_CODE='"+habCodeNew+"')b,"
					+ "(SELECT COUNT(*) FROM RWS_HAB_INSTITUTE_TBL WHERE HAB_CODE='"+habCodeNew+"')c, "
					+ "(SELECT COUNT(*) FROM TEMPSELECTEDHABS_TBL WHERE HAB_CODE='"+habCodeNew+"')f, "
					+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40_CREATED_TBL WHERE HAB_CODE='"+habCodeNew+"')g, "
					+ "(SELECT COUNT(*) FROM RWS_HAB_CONTAMINATION_TBL WHERE HAB_CODE='"+habCodeNew+"')h, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_CONTAMINATION_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeNew+"')i, "
					+ "(SELECT COUNT (*) FROM RWS_HAB_QUAN_QUAL_STAT_TBL WHERE HAB_CODE='"+habCodeNew+"')j, "
					+ "(SELECT COUNT(*) FROM RWS_LPCD_CHECK_STATUS_TBL WHERE PANCH_CODE='"+habCodeNew+"')k,"
					+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40PERCENT_TBL_PREV WHERE HAB_CODE='"+habCodeNew+"')l, "
					+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40PERCENT_TBL WHERE HAB_CODE='"+habCodeNew+"') m, "
					+ "(SELECT COUNT(*) FROM RWS_HABS_UI_NULL_DELETED_TBL WHERE HAB_CODE='"+habCodeNew+"')n, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_MAST_TBL WHERE HAB_CODE='"+habCodeNew+"')o, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_SCHEME_TBL WHERE SUBSTR (SCHEME_CODE,1,16)='"+habCodeNew+"')p, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_SOURCE_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeNew+"')q, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_HAB_TBL WHERE HAB_CODE='"+habCodeNew+"')r, "
					+ "(SELECT COUNT(*) FROM RWS_AST_WTP_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')s, "
					+ "(SELECT COUNT(*) FROM RWS_AST_WTP_SC_PARAM_TBL WHERE SUBSTR(WTPSC_CODE,1,16)='"+habCodeNew+"')t, "
					+ "(SELECT COUNT(*) FROM RWS_AST_WATCHMAN_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')u, "
					+ "(SELECT COUNT(*) FROM RWS_AST_WATCHMAN_PARAM_TBL WHERE SUBSTR(WATCHMAN_CODE,1,16) ='"+habCodeNew+"')v, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SUMP_M_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')w, "
					+ "(SELECT COUNT(*) FROM RWS_AST_BPT_PARAM_TBL WHERE SUBSTR(BPT_CODE,1,16)='"+habCodeNew+"')x, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SUMP_M_SC_PARAM_TBL WHERE SUBSTR(SUMPCODE,1,16)='"+habCodeNew+"')y, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SUBCOMP_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')z, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SUBCOMP_PARAM_TBL WHERE SUBSTR(PUMP_CODE,1,16)='"+habCodeNew+"')a1, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SS_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a2, "
					+ "(SELECT COUNT(*) FROM RWS_AST_SS_SC_PARAM_TBL WHERE SUBSTR(SSSC_CODE,1,16) ='"+habCodeNew+"')a3, "
					+ "(SELECT COUNT(*) FROM RWS_AST_RW_COLLWELL_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a3, "
					+ "(SELECT COUNT(*) FROM RWS_AST_RW_COLLWELL_PARAM_TBL WHERE SUBSTR(RW_COLLWELL_CODE,1,16)='"+habCodeNew+"')a4, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PUMP_DET_SC_PARAM_TBL WHERE SUBSTR(PUMPDET_CODE,1,16)='"+habCodeNew+"')a5, "
					+ "(SELECT COUNT(*) FROM RWS_PUMPINGMAIN_PIPES_TBL WHERE SUBSTR(PM_CODE,1,16)='"+habCodeNew+"')a6, "
					+ "(SELECT COUNT(*) FROM RWS_PUMPINGMAIN_PIPES WHERE SUBSTR(PM_CODE,1,16)='"+habCodeNew+"')a7, "
					+ "(SELECT COUNT(*) FROM RWS_PONDS_MST_TBL WHERE SUBSTR(POND_CODE,1,16)='"+habCodeNew+"')a8, "
					+ "(SELECT COUNT(*) FROM RWS_PONDS_MST_TBL WHERE HAB_CODE='"+habCodeNew+"') a9, "
					+ "(SELECT COUNT(*) FROM RWS_HAB_COMPONENT_TBL WHERE HAB_CODE='"+habCodeNew+"')a10, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeNew+"')a11, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_TBL WHERE HAB_CODE='"+habCodeNew+"')a12, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_HABITATION_TBL WHERE HAB_CODE='"+habCodeNew+"')a13, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_HABITATION_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeNew+"')a14, "
					+ "(SELECT COUNT(*) FROM RWS_SHALLOWHANDPUMPS_TBL WHERE SUBSTR(SHALLOWHP_CODE,1,16)='"+habCodeNew+"')a15, "
					+ "(SELECT COUNT(*) FROM RWS_SHALLOWHANDPUMPS_TBL WHERE HAB_CODE='"+habCodeNew+"')a16, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OHSR_SC_PARAM_TBL WHERE SUBSTR(OHSR_CODE,1,16)='"+habCodeNew+"')a17, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OHBR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a18, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OHBR_SC_PARAM_TBL WHERE SUBSTR(OHBR_CODE,1,16) ='"+habCodeNew+"')a19, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OANDM_PARAM_TBL WHERE SUBSTR(OANDMCODE,1,16)='"+habCodeNew+"') a20, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GRAVITYMAIN_TBL WHERE HAB_CODE='"+habCodeNew+"')a21, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GRAVITYMAIN_TBL WHERE SUBSTR(GRAVITYMAIN_CODE,1,16)='"+habCodeNew+"')a22, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GLSR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a23, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GLSR_SC_PARAM_TBL WHERE SUBSTR(GLSR_CODE,1,16)='"+habCodeNew+"')a24, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GLBR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a25, "
					+ "(SELECT COUNT(*) FROM RWS_AST_GLBR_SC_PARAM_TBL WHERE SUBSTR(GLBR_CODE,1,16) ='"+habCodeNew+"')a26, "
					+ "(SELECT COUNT(*) FROM RWS_AST_FP_BRIDGE_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a27, "
					+ "(SELECT COUNT(*) FROM RWS_AST_FP_BRIDGE_PARAM_TBL WHERE SUBSTR(BRIDGE_CODE,1,16)='"+habCodeNew+"')a28, "
					+ "(SELECT COUNT (*) FROM RWS_AST_DISTRI_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a228, "
					+ "(SELECT COUNT(*) FROM RWS_AST_DISTRI_SC_PARAM_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeNew+"')a29, "
					+ "(SELECT COUNT(*) FROM RWS_AST_DISTRIB_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeNew+"')a30, "
					+ "(SELECT COUNT(*) FROM RWS_AST_DISTRIB_PARAM_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeNew+"')a31, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PUMPINGMAIN_TBL WHERE HAB_CODE='"+habCodeNew+"')a32, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PUMPINGMAIN_TBL WHERE SUBSTR(PUMPINGMAIN_CODE,1,16)='"+habCodeNew+"')a33, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PUMPHOUSE_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a34, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PUMPHOUSE_PARAM_TBL WHERE SUBSTR(PUMPHOUSE_CODE,1,16) ='"+habCodeNew+"')a35, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PM_SC_PARAM_TBL WHERE SUBSTR(PUMPMAIN_CODE,1,16) ='"+habCodeNew+"')a36, "
					+ "(SELECT COUNT(*) FROM RWS_AST_PM_NOOFPIPES_TBL WHERE SUBSTR(PM_CODE,1,16)='"+habCodeNew+"') a37, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OTHERS_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a38, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OTHERS_PARAM_TBL WHERE SUBSTR(OTHER_COMP_CODE,1,16)='"+habCodeNew+"')a39, "
					+ "(SELECT COUNT(*) FROM RWS_AST_OHSR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a40, "
					+ "(SELECT COUNT(*) FROM RWS_OHGLCI_HAB_LINK_TBL WHERE SUBSTR(SUBCOMP_CODE,1,16)='"+habCodeNew+"')a42, "
					+ "(SELECT COUNT(*) FROM RWS_OHGLCI_HAB_LINK_TBL WHERE HAB_CODE='"+habCodeNew+"')a43, "
					+ "(SELECT COUNT(*) FROM RWS_PWS_SP_HC_PC_SC_PARAM_TBL WHERE SUBSTR(SPHCPCSC_CODE,1,16) ='"+habCodeNew+"')a44, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CW_COLLWELL_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a45, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CW_COLLWELL_PARAM_TBL WHERE SUBSTR(CW_COLLWELL_CODE,1,16)='"+habCodeNew+"')a16, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CP_SC_PARAM_TBL WHERE SUBSTR(CPSC_CODE,1,16)='"+habCodeNew+"')a47, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CIS_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a48, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CIS_SC_PARAM_TBL WHERE SUBSTR(CISSC_CODE,1,16)='"+habCodeNew+"')a49, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CHLORINATION_TBL WHERE HAB_CODE='"+habCodeNew+"')a50, "
					+ "(SELECT COUNT(*) FROM RWS_AST_CHLORINATION_TBL WHERE SUBSTR(CL_CODE,1,16) ='"+habCodeNew+"')a51, "
					+ "(SELECT COUNT(*) FROM RWS_AST_BPT_PARAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a52, "
					+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE SUBSTR(POND_CODE,1,16)='"+habCodeNew+"')a53, "
					+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE HAB_CODE='"+habCodeNew+"')a54, "
					+ "(SELECT COUNT(*) FROM RWS_OPEN_WELL_MAST_TBL WHERE SUBSTR (OPENWELL_CODE,1,16)='"+habCodeNew+"')a55, "
					+ "(SELECT COUNT(*) FROM RWS_OPEN_WELL_MAST_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a56, "
					+ "(SELECT COUNT(*) FROM RWS_OPENWELL_POND_TBL WHERE SUBSTR(POND_CODE,1,16) ='"+habCodeNew+"')a57, "
					+ "(SELECT COUNT(*) FROM RWS_OPENWELL_POND_TBL WHERE HAB_CODE='"+habCodeNew+"')a58, "
					+ "(SELECT COUNT(*) FROM RWS_GRAVITYMAIN_PIPES_TBL WHERE SUBSTR(GM_CODE,1,16)='"+habCodeNew+"')a59, "
					+ "(SELECT COUNT(*) FROM RWS_HP_SUBCOMP_PARAM_TBL WHERE SUBSTR(HP_CODE,1,16)='"+habCodeNew+"')a60, "
					+ "(SELECT COUNT(*) FROM RWS_HANDPUMPS_TBL WHERE HAB_CODE='"+habCodeNew+"')a61, "
					+ "(SELECT COUNT(*) FROM RWS_DISTRIBUTION_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16) ='"+habCodeNew+"')a62, "
					+ "(SELECT COUNT(*) FROM RWS_PWS_DISTRIBUTION_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16) ='"+habCodeNew+"')a63, "
					+ "(SELECT COUNT(*) FROM RWS_GLSROHSROHBR_SC_PARAM_TBL WHERE SUBSTR(SCHEME_CODE,1,16) ='"+habCodeNew+"')a64, "
					+ "(SELECT COUNT(*) FROM RWS_WORK_ADMN_TBL WHERE LEAD_HABITATION='"+habCodeNew+"')a65, "
					+ "(SELECT COUNT(*) FROM RWS_ADMN_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a66, "
					+ "(SELECT COUNT(*) FROM RWS_REV_ADM_SANC_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a67, "
					+ "(SELECT COUNT(*) FROM RWS_NEW_REVISED_EST_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeNew+"')a68, "
					+ "(SELECT COUNT(*) FROM RWS_EST_NEW_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a69, "
					+ "(SELECT COUNT(*) FROM RWS_REV_EST_NEW_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"') a70, "
					+ "(SELECT COUNT(*) FROM RWS_SOURCE_IDEN_FIN_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeNew+"')a71, "
					+ "(SELECT COUNT (*) FROM RWS_SOURCE_IDEN_FIN_TBL WHERE HAB_CODE='"+habCodeNew+"')a72, "
					+ "(SELECT COUNT(*) FROM RWS_WORK_COMP_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a73, "
					+ "(SELECT COUNT(*) FROM RWS_PRAJAPADAM_EXIST_SCH_TBL WHERE HAB_CODE='"+habCodeNew+"')a74, "
					+ "(SELECT COUNT(*) FROM RWS_TEMP_PROPOSAL_HAB_TBL WHERE HAB_CODE='"+habCodeNew+"')a75, "
					+ "(SELECT COUNT(*) FROM RWS_TEMP_OM_PROPOSAL_HAB_TBL WHERE HAB_CODE='"+habCodeNew+"')a76, "
					+ "(SELECT COUNT(*) FROM RWS_OM_PROPOSAL_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a77, "
					+ "(SELECT COUNT(*) FROM RWS_DDWS_WORKS_MPR_TBL WHERE HAB_CODE='"+habCodeNew+"')a78, "
					+ "(SELECT COUNT(*) FROM RWS_REP_PROPOSAL_TBL WHERE SUBSTR(LEAD_HAB_CODE,1,16) ='"+habCodeNew+"')a79, "
					+ "(SELECT COUNT(*) FROM RWS_PROPOSAL_HL_MIRROR_TBL WHERE HAB_CODE='"+habCodeNew+"')a80, "
					+ "(SELECT COUNT(*) FROM RWS_PROPOSAL_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a81, "
					+ "(SELECT COUNT(*) FROM RWS_PRAJAPADAM_TBL WHERE HAB_CODE='"+habCodeNew+"')a82, "
					+ "(SELECT COUNT(*) FROM RWS_SCHOOL_MASTER_TBL WHERE HAB_CODE='"+habCodeNew+"')a83, "
					+ "(SELECT COUNT(*) FROM RWS_SCHOOL_ASSET_LNK_TBL WHERE HAB_CODE='"+habCodeNew+"')a84, "
					+ "(SELECT COUNT(*) FROM RWS_DDWS_SCHOOLS_MPR_TBL WHERE HAB_CODE='"+habCodeNew+"')a85, "
					+ "(SELECT COUNT(*) FROM RWS_WATER_SAMPLE_COLLECT_TBL WHERE HAB_CODE='"+habCodeNew+"')a86, "
					+ "(SELECT COUNT(*) FROM RWS_WATER_SAMPLE_COLLECT_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeNew+"')a87, "
					+ "(SELECT COUNT(*) FROM RWS_WQ_TEST_RESULTS_TBL WHERE SUBSTR (SOURCE_CODE,1,16)='"+habCodeNew+"')a88, "
					+ "(SELECT COUNT(*) FROM RWS_FTK_TESTING_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeNew+"')a89, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_TBL WHERE HAB_CODE='"+habCodeNew+"')a90, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_EXIST_SCH_TBL WHERE HAB_CODE='"+habCodeNew+"')a91, "
					+ "(SELECT COUNT(*) FROM RWS_AST_STANDPOST_TBL WHERE substr(STANDPOST_CODE,1,16)='"+habCodeNew+"')a92, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_COMPONENT_IMAGE_TBL WHERE substr(ASSET_COMPONENT,1,16)='"+habCodeNew+"')a93, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_COMPONENT_REPAIR_TBL WHERE substr(ASSET_COMP_CODE,1,16)='"+habCodeNew+"')a94, "
					+ "(SELECT COUNT(*) FROM RWS_MOBILE_SMS_REGISTER_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a95, "
					+ "(SELECT COUNT(*) FROM RWS_TANKER_REG_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a96, "
					+ "(SELECT COUNT(*) FROM RWS_TANKER_SRC_DEST_DIS_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeNew+"')a97, "
					+ "(SELECT COUNT(*) FROM RWS_TANKER_MOVEMENT_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeNew+"')a98, "
					+ "(SELECT COUNT(*) FROM RWS_TANKER_DEST_LOCATION_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a99, "
					+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE HAB_CODE='"+habCodeNew+"')a100, "
					+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE substr(POND_CODE,1,16)='"+habCodeNew+"')a101, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_TANKER_SMS_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a102, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_SSTANK_TBL WHERE HAB_CODE='"+habCodeNew+"')a103, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_SSTANK_TBL WHERE substr(SSSC_CODE,1,16)='"+habCodeNew+"')a104, "
					+ "(SELECT COUNT(*) FROM RWS_SMS_IN_OUT_STATUS_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a105, "
					+ "(SELECT COUNT(*) FROM RWS_SCHEME_STATUS_SMS_TBL WHERE substr(COMPONENT_CODE,1,16)='"+habCodeNew+"')a106, "
					+ "(SELECT COUNT(*) FROM RWS_RESIDUAL_CHLORINE_SMS_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeNew+"')a107, "
					+ "(SELECT COUNT(*) FROM RWS_OHSR_GLSR_SMS_TBL WHERE substr(COMPONENT_CODE,1,16)='"+habCodeNew+"')a108, "
					+ "(SELECT COUNT(*) FROM RWS_PUSHKAR_WORK_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a112, "
					+ "(SELECT COUNT(*) FROM RWS_GENERIC_COMPLAINTS_REG_TBL WHERE HABITATION_CODE='"+habCodeNew+"')a113, "
					+ "(SELECT COUNT(*) FROM RWS_COMPLAINTS_REGISTER_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeNew+"')a114, "
					+ "(SELECT COUNT(*) FROM RWS_DROUGHT_NEWSPAPER_ITEM_TBL WHERE HAB_CODE='"+habCodeNew+"')a115, "
					+ "(SELECT COUNT(*) FROM RWS_ASSET_SOURCE_LNK_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeNew+"')a116 "
					+ "from dual";
			ResultSet rs = getResultSet(q,con1);
			ResultSetMetaData rsmd = rs.getMetaData();
			if(rs.next()){
				if(rs.getInt(1)==0 && rs.getInt(2)==0 && rs.getInt(3)==0){
					statusTracker = "ERROR OCCURED - DATA NOT EXISTS IN MASTER(EXISTING HAB RELATED) TABLES WITH NEW HABCODE";
					b = false;
				}
				for(int k=4;k<=rsmd.getColumnCount();k++){
					if(rs.getInt(k)!=0){
						statusTracker = "ERROR OCCURED - DATA EXISTS IN TRANSACTION(NEW HAB RELATED) TABLES WITH NEW HABCODE / ALREADY CONVERTED";
						b = false;
					}
				}
			}			
			if(b){
					String qq = "SELECT"
						+ "( SELECT COUNT(*) FROM RWS_HABITATION_DIR_DYNA_TBL WHERE HAB_CODE='"+habCodeOld+"')a, "
						+ "(SELECT COUNT(*) FROM RWS_HABMAST_TBL WHERE PRHAB='"+habCodeOld+"')d,"
						+ "(SELECT COUNT(*) FROM RWS_HABMAST_TBL WHERE SUBSTR(HAB_CODE,1,14)='"+habCodeOld.substring(0,14)+"')e, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_SUPPLY_STATUS_TBL WHERE HAB_CODE='"+habCodeOld+"')b, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_INSTITUTE_TBL WHERE HAB_CODE='"+habCodeOld+"')c, "
						+ "(SELECT COUNT(*) FROM TEMPSELECTEDHABS_TBL WHERE HAB_CODE='"+habCodeOld+"')f, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40_CREATED_TBL WHERE HAB_CODE='"+habCodeOld+"')g, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_CONTAMINATION_TBL WHERE HAB_CODE='"+habCodeOld+"')h, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_CONTAMINATION_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"')i, "
						+ "(SELECT COUNT (*) FROM RWS_HAB_QUAN_QUAL_STAT_TBL WHERE HAB_CODE='"+habCodeOld+"')j, "
						+ "(SELECT COUNT(*) FROM RWS_LPCD_CHECK_STATUS_TBL WHERE PANCH_CODE='"+habCodeOld+"')k, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40PERCENT_TBL_PREV WHERE HAB_CODE='"+habCodeOld+"')l, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_DIR_40PERCENT_TBL WHERE HAB_CODE='"+habCodeOld+"') m, "
						+ "(SELECT COUNT(*) FROM RWS_HABS_UI_NULL_DELETED_TBL WHERE HAB_CODE='"+habCodeOld+"')n, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_MAST_TBL WHERE HAB_CODE='"+habCodeOld+"')o, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_SCHEME_TBL WHERE SUBSTR (SCHEME_CODE,1,16)='"+habCodeOld+"')p, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_SOURCE_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeOld+"')q, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_HAB_TBL WHERE HAB_CODE='"+habCodeOld+"')r, "
						+ "(SELECT COUNT(*) FROM RWS_AST_WTP_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')s, "
						+ "(SELECT COUNT(*) FROM RWS_AST_WTP_SC_PARAM_TBL WHERE SUBSTR(WTPSC_CODE,1,16)='"+habCodeOld+"')t, "
						+ "(SELECT COUNT(*) FROM RWS_AST_WATCHMAN_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')u, "
						+ "(SELECT COUNT(*) FROM RWS_AST_WATCHMAN_PARAM_TBL WHERE SUBSTR(WATCHMAN_CODE,1,16) ='"+habCodeOld+"')v, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SUMP_M_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')w, "
						+ "(SELECT COUNT(*) FROM RWS_AST_BPT_PARAM_TBL WHERE SUBSTR(BPT_CODE,1,16)='"+habCodeOld+"')x, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SUMP_M_SC_PARAM_TBL WHERE SUBSTR(SUMPCODE,1,16)='"+habCodeOld+"')y, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SUBCOMP_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')z, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SUBCOMP_PARAM_TBL WHERE SUBSTR(PUMP_CODE,1,16)='"+habCodeOld+"')a1, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SS_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a2, "
						+ "(SELECT COUNT(*) FROM RWS_AST_SS_SC_PARAM_TBL WHERE SUBSTR(SSSC_CODE,1,16) ='"+habCodeOld+"')a3, "
						+ "(SELECT COUNT(*) FROM RWS_AST_RW_COLLWELL_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a3, "
						+ "(SELECT COUNT(*) FROM RWS_AST_RW_COLLWELL_PARAM_TBL WHERE SUBSTR(RW_COLLWELL_CODE,1,16)='"+habCodeOld+"')a4, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PUMP_DET_SC_PARAM_TBL WHERE SUBSTR(PUMPDET_CODE,1,16)='"+habCodeOld+"')a5, "
						+ "(SELECT COUNT(*) FROM RWS_PUMPINGMAIN_PIPES_TBL WHERE SUBSTR(PM_CODE,1,16)='"+habCodeOld+"')a6, "
						+ "(SELECT COUNT(*) FROM RWS_PUMPINGMAIN_PIPES WHERE SUBSTR(PM_CODE,1,16)='"+habCodeOld+"')a7, "
						+ "(SELECT COUNT(*) FROM RWS_PONDS_MST_TBL WHERE SUBSTR(POND_CODE,1,16)='"+habCodeOld+"')a8, "
						+ "(SELECT COUNT(*) FROM RWS_PONDS_MST_TBL WHERE HAB_CODE='"+habCodeOld+"') a9, "
						+ "(SELECT COUNT(*) FROM RWS_HAB_COMPONENT_TBL WHERE HAB_CODE='"+habCodeOld+"')a10, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeOld+"')a11, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_TBL WHERE HAB_CODE='"+habCodeOld+"')a12, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_HABITATION_TBL WHERE HAB_CODE='"+habCodeOld+"')a13, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_HABITATION_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"')a14, "
						+ "(SELECT COUNT(*) FROM RWS_SHALLOWHANDPUMPS_TBL WHERE SUBSTR(SHALLOWHP_CODE,1,16)='"+habCodeOld+"')a15, "
						+ "(SELECT COUNT(*) FROM RWS_SHALLOWHANDPUMPS_TBL WHERE HAB_CODE='"+habCodeOld+"')a16, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OHSR_SC_PARAM_TBL WHERE SUBSTR(OHSR_CODE,1,16)='"+habCodeOld+"')a17, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OHBR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a18, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OHBR_SC_PARAM_TBL WHERE SUBSTR(OHBR_CODE,1,16) ='"+habCodeOld+"')a19, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OANDM_PARAM_TBL WHERE SUBSTR(OANDMCODE,1,16)='"+habCodeOld+"') a20, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GRAVITYMAIN_TBL WHERE HAB_CODE='"+habCodeOld+"')a21, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GRAVITYMAIN_TBL WHERE SUBSTR(GRAVITYMAIN_CODE,1,16)='"+habCodeOld+"')a22, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GLSR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a23, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GLSR_SC_PARAM_TBL WHERE SUBSTR(GLSR_CODE,1,16)='"+habCodeOld+"')a24, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GLBR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a25, "
						+ "(SELECT COUNT(*) FROM RWS_AST_GLBR_SC_PARAM_TBL WHERE SUBSTR(GLBR_CODE,1,16) ='"+habCodeOld+"')a26, "
						+ "(SELECT COUNT(*) FROM RWS_AST_FP_BRIDGE_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a27, "
						+ "(SELECT COUNT(*) FROM RWS_AST_FP_BRIDGE_PARAM_TBL WHERE SUBSTR(BRIDGE_CODE,1,16)='"+habCodeOld+"')a28, "
						+ "(SELECT COUNT (*) FROM RWS_AST_DISTRI_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a228, "
						+ "(SELECT COUNT(*) FROM RWS_AST_DISTRI_SC_PARAM_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"')a29, "
						+ "(SELECT COUNT(*) FROM RWS_AST_DISTRIB_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"')a30, "
						+ "(SELECT COUNT(*) FROM RWS_AST_DISTRIB_PARAM_TBL WHERE SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"')a31, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PUMPINGMAIN_TBL WHERE HAB_CODE='"+habCodeOld+"')a32, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PUMPINGMAIN_TBL WHERE SUBSTR(PUMPINGMAIN_CODE,1,16)='"+habCodeOld+"')a33, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PUMPHOUSE_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a34, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PUMPHOUSE_PARAM_TBL WHERE SUBSTR(PUMPHOUSE_CODE,1,16) ='"+habCodeOld+"')a35, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PM_SC_PARAM_TBL WHERE SUBSTR(PUMPMAIN_CODE,1,16) ='"+habCodeOld+"')a36, "
						+ "(SELECT COUNT(*) FROM RWS_AST_PM_NOOFPIPES_TBL WHERE SUBSTR(PM_CODE,1,16)='"+habCodeOld+"') a37, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OTHERS_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a38, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OTHERS_PARAM_TBL WHERE SUBSTR(OTHER_COMP_CODE,1,16)='"+habCodeOld+"')a39, "
						+ "(SELECT COUNT(*) FROM RWS_AST_OHSR_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a40, "
						+ "(SELECT COUNT(*) FROM RWS_OHGLCI_HAB_LINK_TBL WHERE SUBSTR(SUBCOMP_CODE,1,16)='"+habCodeOld+"')a42, "
						+ "(SELECT COUNT(*) FROM RWS_OHGLCI_HAB_LINK_TBL WHERE HAB_CODE='"+habCodeOld+"')a43, "
						+ "(SELECT COUNT(*) FROM RWS_PWS_SP_HC_PC_SC_PARAM_TBL WHERE SUBSTR(SPHCPCSC_CODE,1,16) ='"+habCodeOld+"')a44, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CW_COLLWELL_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a45, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CW_COLLWELL_PARAM_TBL WHERE SUBSTR(CW_COLLWELL_CODE,1,16)='"+habCodeOld+"')a16, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CP_SC_PARAM_TBL WHERE SUBSTR(CPSC_CODE,1,16)='"+habCodeOld+"')a47, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CIS_SC_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a48, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CIS_SC_PARAM_TBL WHERE SUBSTR(CISSC_CODE,1,16)='"+habCodeOld+"')a49, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CHLORINATION_TBL WHERE HAB_CODE='"+habCodeOld+"')a50, "
						+ "(SELECT COUNT(*) FROM RWS_AST_CHLORINATION_TBL WHERE SUBSTR(CL_CODE,1,16) ='"+habCodeOld+"')a51, "
						+ "(SELECT COUNT(*) FROM RWS_AST_BPT_PARAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a52, "
						+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE SUBSTR(POND_CODE,1,16)='"+habCodeOld+"')a53, "
						+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE HAB_CODE='"+habCodeOld+"')a54, "
						+ "(SELECT COUNT(*) FROM RWS_OPEN_WELL_MAST_TBL WHERE SUBSTR (OPENWELL_CODE,1,16)='"+habCodeOld+"')a55, "
						+ "(SELECT COUNT(*) FROM RWS_OPEN_WELL_MAST_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a56, "
						+ "(SELECT COUNT(*) FROM RWS_OPENWELL_POND_TBL WHERE SUBSTR(POND_CODE,1,16) ='"+habCodeOld+"')a57, "
						+ "(SELECT COUNT(*) FROM RWS_OPENWELL_POND_TBL WHERE HAB_CODE='"+habCodeOld+"')a58, "
						+ "(SELECT COUNT(*) FROM RWS_GRAVITYMAIN_PIPES_TBL WHERE SUBSTR(GM_CODE,1,16)='"+habCodeOld+"')a59, "
						+ "(SELECT COUNT(*) FROM RWS_HP_SUBCOMP_PARAM_TBL WHERE SUBSTR(HP_CODE,1,16)='"+habCodeOld+"')a60, "
						+ "(SELECT COUNT(*) FROM RWS_HANDPUMPS_TBL WHERE HAB_CODE='"+habCodeOld+"')a61, "
						+ "(SELECT COUNT(*) FROM RWS_DISTRIBUTION_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16) ='"+habCodeOld+"')a62, "
						+ "(SELECT COUNT(*) FROM RWS_PWS_DISTRIBUTION_PIPES_TBL WHERE SUBSTR(DISTRISC_CODE,1,16) ='"+habCodeOld+"')a63, "
						+ "(SELECT COUNT(*) FROM RWS_GLSROHSROHBR_SC_PARAM_TBL WHERE SUBSTR(SCHEME_CODE,1,16) ='"+habCodeOld+"')a64, "
						+ "(SELECT COUNT(*) FROM RWS_WORK_ADMN_TBL WHERE LEAD_HABITATION='"+habCodeOld+"')a65, "
						+ "(SELECT COUNT(*) FROM RWS_ADMN_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a66, "
						+ "(SELECT COUNT(*) FROM RWS_REV_ADM_SANC_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a67, "
						+ "(SELECT COUNT(*) FROM RWS_NEW_REVISED_EST_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"')a68, "
						+ "(SELECT COUNT(*) FROM RWS_EST_NEW_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a69, "
						+ "(SELECT COUNT(*) FROM RWS_REV_EST_NEW_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"') a70, "
						+ "(SELECT COUNT(*) FROM RWS_SOURCE_IDEN_FIN_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"')a71, "
						+ "(SELECT COUNT (*) FROM RWS_SOURCE_IDEN_FIN_TBL WHERE HAB_CODE='"+habCodeOld+"')a72, "
						+ "(SELECT COUNT(*) FROM RWS_WORK_COMP_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a73, "
						+ "(SELECT COUNT(*) FROM RWS_PRAJAPADAM_EXIST_SCH_TBL WHERE HAB_CODE='"+habCodeOld+"')a74, "
						+ "(SELECT COUNT(*) FROM RWS_TEMP_PROPOSAL_HAB_TBL WHERE HAB_CODE='"+habCodeOld+"')a75, "
						+ "(SELECT COUNT(*) FROM RWS_TEMP_OM_PROPOSAL_HAB_TBL WHERE HAB_CODE='"+habCodeOld+"')a76, "
						+ "(SELECT COUNT(*) FROM RWS_OM_PROPOSAL_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a77, "
						+ "(SELECT COUNT(*) FROM RWS_DDWS_WORKS_MPR_TBL WHERE HAB_CODE='"+habCodeOld+"')a78, "
						+ "(SELECT COUNT(*) FROM RWS_REP_PROPOSAL_TBL WHERE SUBSTR(LEAD_HAB_CODE,1,16) ='"+habCodeOld+"')a79, "
						+ "(SELECT COUNT(*) FROM RWS_PROPOSAL_HL_MIRROR_TBL WHERE HAB_CODE='"+habCodeOld+"')a80, "
						+ "(SELECT COUNT(*) FROM RWS_PROPOSAL_HAB_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a81, "
						+ "(SELECT COUNT(*) FROM RWS_PRAJAPADAM_TBL WHERE HAB_CODE='"+habCodeOld+"')a82, "
						+ "(SELECT COUNT(*) FROM RWS_SCHOOL_MASTER_TBL WHERE HAB_CODE='"+habCodeOld+"')a83, "
						+ "(SELECT COUNT(*) FROM RWS_SCHOOL_ASSET_LNK_TBL WHERE HAB_CODE='"+habCodeOld+"')a84, "
						+ "(SELECT COUNT(*) FROM RWS_DDWS_SCHOOLS_MPR_TBL WHERE HAB_CODE='"+habCodeOld+"')a85, "
						+ "(SELECT COUNT(*) FROM RWS_WATER_SAMPLE_COLLECT_TBL WHERE HAB_CODE='"+habCodeOld+"')a86, "
						+ "(SELECT COUNT(*) FROM RWS_WATER_SAMPLE_COLLECT_TBL WHERE SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"')a87, "
						+ "(SELECT COUNT(*) FROM RWS_WQ_TEST_RESULTS_TBL WHERE SUBSTR (SOURCE_CODE,1,16)='"+habCodeOld+"')a88, "
						+ "(SELECT COUNT(*) FROM RWS_FTK_TESTING_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeOld+"')a89, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_TBL WHERE HAB_CODE='"+habCodeOld+"')a90, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_EXIST_SCH_TBL WHERE HAB_CODE='"+habCodeOld+"')a91, "
						+ "(SELECT COUNT(*) FROM RWS_AST_STANDPOST_TBL WHERE substr(STANDPOST_CODE,1,16)='"+habCodeOld+"')a92, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_COMPONENT_IMAGE_TBL WHERE substr(ASSET_COMPONENT,1,16)='"+habCodeOld+"')a93, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_COMPONENT_REPAIR_TBL WHERE substr(ASSET_COMP_CODE,1,16)='"+habCodeOld+"')a94, "
						+ "(SELECT COUNT(*) FROM RWS_MOBILE_SMS_REGISTER_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a95, "
						+ "(SELECT COUNT(*) FROM RWS_TANKER_REG_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a96, "
						+ "(SELECT COUNT(*) FROM RWS_TANKER_SRC_DEST_DIS_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeOld+"')a97, "
						+ "(SELECT COUNT(*) FROM RWS_TANKER_MOVEMENT_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeOld+"')a98, "
						+ "(SELECT COUNT(*) FROM RWS_TANKER_DEST_LOCATION_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a99, "
						+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE HAB_CODE='"+habCodeOld+"')a100, "
						+ "(SELECT COUNT(*) FROM RWS_DWTANK_MST_TBL WHERE substr(POND_CODE,1,16)='"+habCodeOld+"')a101, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_TANKER_SMS_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a102, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_SSTANK_TBL WHERE HAB_CODE='"+habCodeOld+"')a103, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_SSTANK_TBL WHERE substr(SSSC_CODE,1,16)='"+habCodeOld+"')a104, "
						+ "(SELECT COUNT(*) FROM RWS_SMS_IN_OUT_STATUS_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a105, "
						+ "(SELECT COUNT(*) FROM RWS_SCHEME_STATUS_SMS_TBL WHERE substr(COMPONENT_CODE,1,16)='"+habCodeOld+"')a106, "
						+ "(SELECT COUNT(*) FROM RWS_RESIDUAL_CHLORINE_SMS_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeOld+"')a107, "
						+ "(SELECT COUNT(*) FROM RWS_OHSR_GLSR_SMS_TBL WHERE substr(COMPONENT_CODE,1,16)='"+habCodeOld+"')a108, "
						+ "(SELECT COUNT(*) FROM RWS_PUSHKAR_WORK_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a112, "
						+ "(SELECT COUNT(*) FROM RWS_GENERIC_COMPLAINTS_REG_TBL WHERE HABITATION_CODE='"+habCodeOld+"')a113, "
						+ "(SELECT COUNT(*) FROM RWS_COMPLAINTS_REGISTER_TBL WHERE substr(SOURCE_CODE,1,16)='"+habCodeOld+"')a114, "
						+ "(SELECT COUNT(*) FROM RWS_DROUGHT_NEWSPAPER_ITEM_TBL WHERE HAB_CODE='"+habCodeOld+"')a115, "
						+ "(SELECT COUNT(*) FROM RWS_ASSET_SOURCE_LNK_TBL WHERE SUBSTR(SOURCE_CODE,1,16) ='"+habCodeOld+"')a116 "
						+ "from dual";
				ResultSet rss = getResultSet(qq,con1);
				ResultSetMetaData rsmdd = rss.getMetaData();
				if(rss.next()){
					int k,j;
					for( k=1,j=0;k<=rsmdd.getColumnCount();k++,j++){
						
						oldValues[j]=rss.getString(k);
						if(!oldValues[j].equals("0")){
							returnValue[j]=-1;
						}
					}
					//System.out.println("last value :     "+j);
				}
			
				statusTracker = "ERROR OCCURED - INSERTION IN MIRROR TABLE";
				String q1 = "insert into rws_master_data_conver_mir_tbl values ('"+habCodeOld+"','"+habCodeNew+"','F',sysdate)";
				executeUpdating1(q1,con1);				
				Statement updateSt = con.createStatement();			
				if(!oldValues[0].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HABITATION_DIR_DYNA_TBL";
					String q2 = "";
					if(!coveredStatus.equals("LAST")){
						q2 = "update RWS_HABITATION_DIR_DYNA_TBL a set (a.DIVISION_OFFICE_CODE,a.SUBDIVISION_OFFICE_CODE,a.CENSUS_YEAR,a.CENSUS_PLAIN_POPU,a.CENSUS_SC_POPU,a.CENSUS_ST_POPU,a.FLOAT_POP,a.FLOAT_POP_REASONS,a.STATUS_DATE,a.PLAIN_POPU_COVERED,a.SC_POP_COVERED,a.ST_POP_COVERED,a.TOTAL_WATER_SUPPLY,a.EXIST_WATER_LEVEL,a.COVERAGE_STATUS,a.NEAR_SURFACE_SOURCE,a.NEAR_GROUND_SOURCE,a.REMARKS,a.QUALITY_AFFECTED,a.UPDATE_DATE,a.PREVIOUS_YR_STATUS,a.PRESENT_YR_STATUS,a.PROPOSED_FC_YEAR,a.PROPOSED_FC_EST_AMT,a.HABITATION_TYPE,a.HOUSEHOLD_NO,a.SLIPPAGE_CODE,a.NO_OF_CATTLE,a.HABITATION_CATEGORY,a.EXISTING_SOURCES_NO,a.SAFE_SOURCES_NO,a.HABITATION_SUB_TYPE,a.NC_SOURCE_TYPE,a.SOURCE_DISTANCE,a.LPCD_COOKING,a.POPU_PERCENT_COVERED)=( select b.DIVISION_OFFICE_CODE,b.SUBDIVISION_OFFICE_CODE,b.CENSUS_YEAR,b.CENSUS_PLAIN_POPU,b.CENSUS_SC_POPU,b.CENSUS_ST_POPU,b.FLOAT_POP,b.FLOAT_POP_REASONS,b.STATUS_DATE,b.PLAIN_POPU_COVERED,b.SC_POP_COVERED,b.ST_POP_COVERED,b.TOTAL_WATER_SUPPLY,b.EXIST_WATER_LEVEL,'"+coveredStatus+"' as COVERAGE_STATUS,b.NEAR_SURFACE_SOURCE,b.NEAR_GROUND_SOURCE,b.REMARKS,b.QUALITY_AFFECTED,b.UPDATE_DATE,b.PREVIOUS_YR_STATUS,b.PRESENT_YR_STATUS,b.PROPOSED_FC_YEAR,b.PROPOSED_FC_EST_AMT,b.HABITATION_TYPE,b.HOUSEHOLD_NO,b.SLIPPAGE_CODE,b.NO_OF_CATTLE,b.HABITATION_CATEGORY,b.EXISTING_SOURCES_NO,b.SAFE_SOURCES_NO,b.HABITATION_SUB_TYPE,b.NC_SOURCE_TYPE,b.SOURCE_DISTANCE,b.LPCD_COOKING,b.POPU_PERCENT_COVERED from RWS_HABITATION_DIR_DYNA_TBL b where b.hab_code='"+habCodeOld+"') where a.hab_code='"+habCodeNew+"'";
					}
					else{
						q2 = "update RWS_HABITATION_DIR_DYNA_TBL a set (a.DIVISION_OFFICE_CODE,a.SUBDIVISION_OFFICE_CODE,a.CENSUS_YEAR,a.CENSUS_PLAIN_POPU,a.CENSUS_SC_POPU,a.CENSUS_ST_POPU,a.FLOAT_POP,a.FLOAT_POP_REASONS,a.STATUS_DATE,a.PLAIN_POPU_COVERED,a.SC_POP_COVERED,a.ST_POP_COVERED,a.TOTAL_WATER_SUPPLY,a.EXIST_WATER_LEVEL,a.COVERAGE_STATUS,a.NEAR_SURFACE_SOURCE,a.NEAR_GROUND_SOURCE,a.REMARKS,a.QUALITY_AFFECTED,a.UPDATE_DATE,a.PREVIOUS_YR_STATUS,a.PRESENT_YR_STATUS,a.PROPOSED_FC_YEAR,a.PROPOSED_FC_EST_AMT,a.HABITATION_TYPE,a.HOUSEHOLD_NO,a.SLIPPAGE_CODE,a.NO_OF_CATTLE,a.HABITATION_CATEGORY,a.EXISTING_SOURCES_NO,a.SAFE_SOURCES_NO,a.HABITATION_SUB_TYPE,a.NC_SOURCE_TYPE,a.SOURCE_DISTANCE,a.LPCD_COOKING,a.POPU_PERCENT_COVERED)=( select b.DIVISION_OFFICE_CODE,b.SUBDIVISION_OFFICE_CODE,b.CENSUS_YEAR,b.CENSUS_PLAIN_POPU,b.CENSUS_SC_POPU,b.CENSUS_ST_POPU,b.FLOAT_POP,b.FLOAT_POP_REASONS,b.STATUS_DATE,b.PLAIN_POPU_COVERED,b.SC_POP_COVERED,b.ST_POP_COVERED,b.TOTAL_WATER_SUPPLY,b.EXIST_WATER_LEVEL,b.PREVIOUS_YR_STATUS as COVERAGE_STATUS,b.NEAR_SURFACE_SOURCE,b.NEAR_GROUND_SOURCE,b.REMARKS,b.QUALITY_AFFECTED,b.UPDATE_DATE,b.PREVIOUS_YR_STATUS,b.PRESENT_YR_STATUS,b.PROPOSED_FC_YEAR,b.PROPOSED_FC_EST_AMT,b.HABITATION_TYPE,b.HOUSEHOLD_NO,b.SLIPPAGE_CODE,b.NO_OF_CATTLE,b.HABITATION_CATEGORY,b.EXISTING_SOURCES_NO,b.SAFE_SOURCES_NO,b.HABITATION_SUB_TYPE,b.NC_SOURCE_TYPE,b.SOURCE_DISTANCE,b.LPCD_COOKING,b.POPU_PERCENT_COVERED from RWS_HABITATION_DIR_DYNA_TBL b where b.hab_code='"+habCodeOld+"') where a.hab_code='"+habCodeNew+"'";
					}
					iter = 0;
					returnValue[0]=executeUpdating(q2,con);
				}
				if(!oldValues[3].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_SUPPLY_STATUS_TBL";
					String q3 = "UPDATE RWS_HAB_SUPPLY_STATUS_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 1;
					returnValue[3]=returnValue[0]=executeUpdating(q3,con);
				}
				if(!oldValues[4].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_INSTITUTE_TBL";
					String q4 = "UPDATE RWS_HAB_INSTITUTE_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 2;
					returnValue[4]=executeUpdating(q4,con);
				}
				if(!oldValues[5].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN TEMPSELECTEDHABS_TBL";
					String q5 = "UPDATE TEMPSELECTEDHABS_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 3;
					returnValue[5]=executeUpdating(q5,con);
				}
				if(!oldValues[6].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_DIR_40_CREATED_TBL";
					String q6 = "UPDATE RWS_HAB_DIR_40_CREATED_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 4;
					returnValue[6]=executeUpdating(q6,con);
				}
				if(!oldValues[7].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_CONTAMINATION_TBL";
					String q61 = "UPDATE RWS_HAB_CONTAMINATION_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 5;
					returnValue[7]=executeUpdating(q61,con);
				}
				if(!oldValues[8].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_CONTAMINATION_TBL";
					String q7 = "UPDATE RWS_SOURCE_CONTAMINATION_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 6;
					returnValue[8]=executeUpdating(q7,con);
				}
				if(!oldValues[9].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_QUAN_QUAL_STAT_TBL";
					String q8 = "UPDATE RWS_HAB_QUAN_QUAL_STAT_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 7;
					returnValue[9]=executeUpdating(q8,con);
				}
				if(!oldValues[10].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_LPCD_CHECK_STATUS_TBL";
					String q9 = "UPDATE RWS_LPCD_CHECK_STATUS_TBL SET PANCH_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 8;
					returnValue[10]=executeUpdating(q9,con);
				}
				if(!oldValues[11].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_DIR_40PERCENT_TBL_PREV";
					String q10 = "UPDATE RWS_HAB_DIR_40PERCENT_TBL_PREV SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 9;
					returnValue[11]=executeUpdating(q10,con);
				}
				if(!oldValues[12].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_DIR_40PERCENT_TBL";
					String q11 = "UPDATE RWS_HAB_DIR_40PERCENT_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 10;
					returnValue[12]=executeUpdating(q11,con);
				}
				if(!oldValues[13].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HABS_UI_NULL_DELETED_TBL";
					String q12 = "UPDATE RWS_HABS_UI_NULL_DELETED_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 11;
					returnValue[13]=executeUpdating(q12,con);
				}
				if(!oldValues[14].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_MAST_TBL";
					String q13 = "UPDATE RWS_ASSET_MAST_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 12;
					returnValue[14]=executeUpdating(q13,con);
				}
				if(!oldValues[15].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_SCHEME_TBL";
					String q14 = "UPDATE RWS_ASSET_SCHEME_TBL SET SCHEME_CODE='"+habCodeNew+"'||SUBSTR(SCHEME_CODE,17,24) where SUBSTR(SCHEME_CODE,1,16)='"+habCodeOld+"'";
					iter = 13;
					returnValue[15]=executeUpdating(q14,con);
				}
				if(!oldValues[16].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_SOURCE_TBL";
					String q15 = "UPDATE RWS_ASSET_SOURCE_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 14;
					returnValue[16]=executeUpdating(q15,con);
				}
				if(!oldValues[17].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_HAB_TBL";
					String q16 = "UPDATE RWS_ASSET_HAB_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 15;
					returnValue[17]=executeUpdating(q16,con);
				}
				if(!oldValues[18].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_WTP_SC_PARAM_TBL";
					String q17 = "UPDATE RWS_AST_WTP_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 16;
					returnValue[18]=executeUpdating(q17,con);
				}
				if(!oldValues[19].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_WTP_SC_PARAM_TBL";
					String q18 = "UPDATE RWS_AST_WTP_SC_PARAM_TBL SET WTPSC_CODE='"+habCodeNew+"'||SUBSTR(WTPSC_CODE,17,24) where SUBSTR(WTPSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 17;
					returnValue[19]=executeUpdating(q18,con);
				}
				if(!oldValues[20].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_WATCHMAN_PARAM_TBL";
					String q19 = "UPDATE RWS_AST_WATCHMAN_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 18;
					returnValue[20]=executeUpdating(q19,con);
				}
				if(!oldValues[21].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_WATCHMAN_PARAM_TBL";
					String q20 = "UPDATE RWS_AST_WATCHMAN_PARAM_TBL SET WATCHMAN_CODE='"+habCodeNew+"'||SUBSTR(WATCHMAN_CODE,17,24) where SUBSTR(WATCHMAN_CODE,1,16)='"+habCodeOld+"'";
					iter = 19;
					returnValue[21]=executeUpdating(q20,con);
				}
				if(!oldValues[22].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SUMP_M_SC_PARAM_TBL";
					String q21 = "UPDATE RWS_AST_SUMP_M_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 20;
					returnValue[22]=executeUpdating(q21,con);
				}
				if(!oldValues[23].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_BPT_PARAM_TBL";
					String q22 = "UPDATE RWS_AST_BPT_PARAM_TBL SET BPT_CODE='"+habCodeNew+"'||SUBSTR(BPT_CODE,17,24) where SUBSTR(BPT_CODE,1,16)='"+habCodeOld+"'";
					iter = 21;
					returnValue[23]=executeUpdating(q22,con);
				}
				if(!oldValues[24].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SUMP_M_SC_PARAM_TBL";
					String q23 = "UPDATE RWS_AST_SUMP_M_SC_PARAM_TBL SET SUMPCODE='"+habCodeNew+"'||SUBSTR(SUMPCODE,17,24) where SUBSTR(SUMPCODE,1,16)='"+habCodeOld+"'";
					iter = 22;
					returnValue[24]=executeUpdating(q23,con);
				}
				if(!oldValues[25].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SUBCOMP_PARAM_TBL";
					String q24 = "UPDATE RWS_AST_SUBCOMP_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 23;
					returnValue[25]=executeUpdating(q24,con);
				}
				if(!oldValues[26].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SUBCOMP_PARAM_TBL";
					String q25 = "UPDATE RWS_AST_SUBCOMP_PARAM_TBL SET PUMP_CODE='"+habCodeNew+"'||SUBSTR(PUMP_CODE,17,24) where SUBSTR(PUMP_CODE,1,16)='"+habCodeOld+"'";
					iter = 24;
					returnValue[26]=executeUpdating(q25,con);
				}
				if(!oldValues[27].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SS_SC_PARAM_TBL";
					String q26 = "UPDATE RWS_AST_SS_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 25;
					returnValue[27]=executeUpdating(q26,con);
				}
				if(!oldValues[28].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_SS_SC_PARAM_TBL";
					String q27 = "UPDATE RWS_AST_SS_SC_PARAM_TBL SET SSSC_CODE='"+habCodeNew+"'||SUBSTR(SSSC_CODE,17,24) where SUBSTR(SSSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 26;
					returnValue[28]=executeUpdating(q27,con);
				}
				if(!oldValues[29].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_RW_COLLWELL_PARAM_TBL";
					String q28 = "UPDATE RWS_AST_RW_COLLWELL_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 27;
					returnValue[29]=executeUpdating(q28,con);
				}
				if(!oldValues[30].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_RW_COLLWELL_PARAM_TBL";
					String q29 = "UPDATE RWS_AST_RW_COLLWELL_PARAM_TBL SET RW_COLLWELL_CODE='"+habCodeNew+"'||SUBSTR(RW_COLLWELL_CODE,17,24) where SUBSTR(RW_COLLWELL_CODE,1,16)='"+habCodeOld+"'";
					iter = 28;
					returnValue[30]=executeUpdating(q29,con);
				}
				if(!oldValues[31].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PUMP_DET_SC_PARAM_TBL";
					String q30 = "UPDATE RWS_AST_PUMP_DET_SC_PARAM_TBL SET PUMPDET_CODE='"+habCodeNew+"'||SUBSTR(PUMPDET_CODE,17,24) where SUBSTR(PUMPDET_CODE,1,16)='"+habCodeOld+"'";
					iter = 29;
					returnValue[31]=executeUpdating(q30,con);
				}
				if(!oldValues[32].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PUMPINGMAIN_PIPES_TBL";
					String q31 = "UPDATE RWS_PUMPINGMAIN_PIPES_TBL SET PM_CODE ='"+habCodeNew+"'||SUBSTR(PM_CODE,17,24) where SUBSTR(PM_CODE,1,16)='"+habCodeOld+"'";
					iter = 30;
					returnValue[32]=executeUpdating(q31,con);
				}
				if(!oldValues[33].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PUMPINGMAIN_PIPES";
					String q32 = "UPDATE RWS_PUMPINGMAIN_PIPES SET PM_CODE ='"+habCodeNew+"'||SUBSTR(PM_CODE,17,24) where SUBSTR(PM_CODE,1,16)='"+habCodeOld+"'";
					iter = 31;
					returnValue[33]=executeUpdating(q32,con);
				}
				if(!oldValues[34].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PONDS_MST_TBL";
					String q33 = "UPDATE RWS_PONDS_MST_TBL SET POND_CODE ='"+habCodeNew+"'||SUBSTR(POND_CODE,17,24) where SUBSTR(POND_CODE,1,16)='"+habCodeOld+"'";
					iter = 32;
					returnValue[34]=executeUpdating(q33,con);
				}
				if(!oldValues[35].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PONDS_MST_TBL";
					String q34 = "UPDATE RWS_PONDS_MST_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 33;
					returnValue[35]=executeUpdating(q34,con);
				}
				if(!oldValues[36].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HAB_COMPONENT_TBL";
					String q35 = "UPDATE RWS_HAB_COMPONENT_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 34;
					returnValue[36]=executeUpdating(q35,con);
				}
				
				//System.out.println("source link table executingg---------------"+oldValues[139]);
				//String[] astcode=new String[50];
				//String[] soucode=new String[50];
				ArrayList<String> astcode = new ArrayList<String>();
				ArrayList<String> soucode = new ArrayList<String>();
				int i=0;
				if(!oldValues[139].equals("0")){					
					String dlQuery="select source_code,asset_code from RWS_ASSET_SOURCE_LNK_TBL where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					Statement st=con.createStatement();
					ResultSet rs1=st.executeQuery(dlQuery);					
					while(rs1.next()){
						astcode.add(rs1.getString(2));
						soucode.add(rs1.getString(1));
						/*soucode[i] = rs1.getString(1);
						astcode[i]=rs1.getString(2);*/
						i++;
					}
					//System.out.println("source link table executingg---------where------"+i);
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_SOURCE_LNK_TBL";
					String q139 = "DELETE from  RWS_ASSET_SOURCE_LNK_TBL where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 139;
					returnValue[139]=executeUpdating(q139,con);
				}
				if(!oldValues[37].equals("0")){
					//System.out.println("source  table executingg------------------");
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_TBL";
					String q36 = "UPDATE RWS_SOURCE_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 35;
					returnValue[37]=executeUpdating(q36,con);
					Statement inst= con.createStatement();
					statusTracker = "ERROR OCCURED - INSERTING SOURCE IN RWS_ASSET_SOURCE_LNK_TBL";
					for(int l=0;l<i;l++){
						//System.out.println("source   valu e"+habCodeNew+soucode[l].substring(soucode[l].length()-8));
						//System.out.println("insert into RWS_ASSET_SOURCE_LNK_TBL(source_code,asset_code)(select source_code,'"+astcode[l]+"' from RWS_SOURCE_TBL where SOURCE_CODE='"+habCodeNew+soucode[l].substring(soucode[l].length()-8)+"' )");
						returnValue[139]+= inst.executeUpdate("insert into RWS_ASSET_SOURCE_LNK_TBL(SOURCE_CODE,asset_code)(select SOURCE_CODE,'"+astcode.get(l)+"' from RWS_SOURCE_TBL where SOURCE_CODE='"+habCodeNew+soucode.get(l).substring(soucode.get(l).length()-8)+"' )");
					}				 
					
				}
				if(!oldValues[38].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_TBL";
					String q37 = "UPDATE RWS_SOURCE_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 36;
					returnValue[38]=executeUpdating(q37,con);
				}
				if(!oldValues[39].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_HABITATION_TBL";
					String q38 = "UPDATE RWS_SOURCE_HABITATION_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 37;
					returnValue[39]=executeUpdating(q38,con);
				}
				if(!oldValues[40].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_HABITATION_TBL";
					String q39 = "UPDATE RWS_SOURCE_HABITATION_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 38;
					returnValue[40]=executeUpdating(q39,con);
				}
				if(!oldValues[41].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SHALLOWHANDPUMPS_TBL";
					String q40 = "UPDATE RWS_SHALLOWHANDPUMPS_TBL SET SHALLOWHP_CODE='"+habCodeNew+"'||SUBSTR(SHALLOWHP_CODE,17,24) where SUBSTR(SHALLOWHP_CODE,1,16)='"+habCodeOld+"'";
					iter = 39;
					returnValue[41]=executeUpdating(q40,con);
				}
				if(!oldValues[42].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SHALLOWHANDPUMPS_TBL";
					String q41 = "UPDATE RWS_SHALLOWHANDPUMPS_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 40;
					returnValue[42]=executeUpdating(q41,con);
				}
				if(!oldValues[43].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OHSR_SC_PARAM_TBL";
					String q42 = "UPDATE RWS_AST_OHSR_SC_PARAM_TBL SET OHSR_CODE='"+habCodeNew+"'||SUBSTR(OHSR_CODE,17,24) where SUBSTR(OHSR_CODE,1,16)='"+habCodeOld+"'";
					iter = 41;
					returnValue[43]=executeUpdating(q42,con);
				}
				if(!oldValues[44].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OHBR_SC_PARAM_TBL";
					String q43 = "UPDATE RWS_AST_OHBR_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 42;
					returnValue[44]=executeUpdating(q43,con);
				}
				if(!oldValues[45].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OHBR_SC_PARAM_TBL";
					String q44 = "UPDATE RWS_AST_OHBR_SC_PARAM_TBL SET OHBR_CODE='"+habCodeNew+"'||SUBSTR(OHBR_CODE,17,24) where SUBSTR(OHBR_CODE,1,16)='"+habCodeOld+"'";
					iter = 43;
					returnValue[45]=executeUpdating(q44,con);
				}
				if(!oldValues[46].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OANDM_PARAM_TBL";
					String q45 = "UPDATE RWS_AST_OANDM_PARAM_TBL SET OANDMCODE='"+habCodeNew+"'||SUBSTR(OANDMCODE,17,24) where SUBSTR(OANDMCODE,1,16)='"+habCodeOld+"'";
					iter = 44;
					returnValue[46]=executeUpdating(q45,con);
				}
				if(!oldValues[47].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GRAVITYMAIN_TBL";
					String q46 = "UPDATE RWS_AST_GRAVITYMAIN_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 45;
					returnValue[47]=executeUpdating(q46,con);
				}
				if(!oldValues[48].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GRAVITYMAIN_TBL";
					String q47 = "UPDATE RWS_AST_GRAVITYMAIN_TBL SET GRAVITYMAIN_CODE='"+habCodeNew+"'||SUBSTR(GRAVITYMAIN_CODE,17,24) where SUBSTR(GRAVITYMAIN_CODE,1,16)='"+habCodeOld+"'";
					iter = 46;
					returnValue[48]=executeUpdating(q47,con);
				}
				if(!oldValues[49].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GLSR_SC_PARAM_TBL";
					String q48 = "UPDATE RWS_AST_GLSR_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 47;
					returnValue[49]=executeUpdating(q48,con);
				}
				if(!oldValues[50].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GLSR_SC_PARAM_TBL";
					String q49 = "UPDATE RWS_AST_GLSR_SC_PARAM_TBL SET GLSR_CODE='"+habCodeNew+"'||SUBSTR(GLSR_CODE,17,24) where SUBSTR(GLSR_CODE,1,16)='"+habCodeOld+"'";
					iter = 48;
					returnValue[50]=executeUpdating(q49,con);
				}
				if(!oldValues[51].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GLBR_SC_PARAM_TBL";
					String q50 = "UPDATE RWS_AST_GLBR_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 49;
					returnValue[51]=executeUpdating(q50,con);
				}
				if(!oldValues[52].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_GLBR_SC_PARAM_TBL";
					String q51 = "UPDATE RWS_AST_GLBR_SC_PARAM_TBL SET GLBR_CODE='"+habCodeNew+"'||SUBSTR(GLBR_CODE,17,24) where SUBSTR(GLBR_CODE,1,16)='"+habCodeOld+"'";
					iter = 50;
					returnValue[52]=executeUpdating(q51,con);
				}
				if(!oldValues[53].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_FP_BRIDGE_PARAM_TBL";
					String q52 = "UPDATE RWS_AST_FP_BRIDGE_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 51;
					returnValue[53]=executeUpdating(q52,con);
				}
				if(!oldValues[54].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_FP_BRIDGE_PARAM_TBL";
					String q53 = "UPDATE RWS_AST_FP_BRIDGE_PARAM_TBL SET BRIDGE_CODE ='"+habCodeNew+"'||SUBSTR(BRIDGE_CODE,17,24) where SUBSTR(BRIDGE_CODE,1,16)='"+habCodeOld+"'";
					iter = 52;
					returnValue[54]=executeUpdating(q53,con);
				}
				if(!oldValues[55].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_DISTRI_SC_PARAM_TBL";
					String q54 = "UPDATE RWS_AST_DISTRI_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 53;
					returnValue[55]=executeUpdating(q54,con);
				}
				if(!oldValues[56].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_DISTRI_SC_PARAM_TBL";
					String q55 = "UPDATE RWS_AST_DISTRI_SC_PARAM_TBL SET DISTRISC_CODE='"+habCodeNew+"'||SUBSTR(DISTRISC_CODE,17,24) where SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"'";
					iter = 54;
					returnValue[56]=executeUpdating(q55,con);
				}
				if(!oldValues[57].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_DISTRIB_PIPES_TBL";
					String q56 = "UPDATE RWS_AST_DISTRIB_PIPES_TBL SET DISTRISC_CODE='"+habCodeNew+"'||SUBSTR(DISTRISC_CODE,17,24) where SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"'";
					iter = 55;
					returnValue[57]=executeUpdating(q56,con);
				}
				if(!oldValues[58].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_DISTRIB_PARAM_TBL";
					String q57 = "UPDATE RWS_AST_DISTRIB_PARAM_TBL SET DISTRISC_CODE='"+habCodeNew+"'||SUBSTR(DISTRISC_CODE,17,24) where SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"'";
					iter = 56;
					returnValue[58]=executeUpdating(q57,con);
				}
				if(!oldValues[59].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PUMPINGMAIN_TBL";
					String q58 = "UPDATE RWS_AST_PUMPINGMAIN_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 57;
					returnValue[59]=executeUpdating(q58,con);
				}
				if(!oldValues[60].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PUMPINGMAIN_TBL";
					String q59 = "UPDATE RWS_AST_PUMPINGMAIN_TBL SET PUMPINGMAIN_CODE='"+habCodeNew+"'||SUBSTR(PUMPINGMAIN_CODE,17,24) where SUBSTR(PUMPINGMAIN_CODE,1,16)='"+habCodeOld+"'";
					iter = 58;
					returnValue[60]=executeUpdating(q59,con);
				}
				if(!oldValues[61].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PUMPHOUSE_PARAM_TBL";
					String q60 = "UPDATE RWS_AST_PUMPHOUSE_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 59;
					returnValue[61]=executeUpdating(q60,con);
				}
				if(!oldValues[62].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PUMPHOUSE_PARAM_TBL";
					String q61 = "UPDATE RWS_AST_PUMPHOUSE_PARAM_TBL SET PUMPHOUSE_CODE='"+habCodeNew+"'||SUBSTR(PUMPHOUSE_CODE,17,24) where SUBSTR(PUMPHOUSE_CODE,1,16)='"+habCodeOld+"'";
					iter = 60;
					returnValue[62]=executeUpdating(q61,con);
				}
				if(!oldValues[63].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PM_SC_PARAM_TBL";
					String q62 = "UPDATE RWS_AST_PM_SC_PARAM_TBL SET PUMPMAIN_CODE ='"+habCodeNew+"'||SUBSTR(PUMPMAIN_CODE,17,24) where SUBSTR(PUMPMAIN_CODE,1,16)='"+habCodeOld+"'";
					iter = 61;
					returnValue[63]=executeUpdating(q62,con);
				}
				if(!oldValues[64].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_PM_NOOFPIPES_TBL";
					String q63 = "UPDATE RWS_AST_PM_NOOFPIPES_TBL SET PM_CODE='"+habCodeNew+"'||SUBSTR(PM_CODE,17,24) where SUBSTR(PM_CODE,1,16)='"+habCodeOld+"'";
					iter = 62;
					returnValue[64]=executeUpdating(q63,con);
				}
				if(!oldValues[65].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OTHERS_PARAM_TBL";
					String q64 = "UPDATE RWS_AST_OTHERS_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 63;
					returnValue[65]=executeUpdating(q64,con);
				}
				if(!oldValues[66].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OTHERS_PARAM_TBL";
					String q65 = "UPDATE RWS_AST_OTHERS_PARAM_TBL SET OTHER_COMP_CODE='"+habCodeNew+"'||SUBSTR(OTHER_COMP_CODE,17,24) where SUBSTR(OTHER_COMP_CODE,1,16)='"+habCodeOld+"'";
					iter = 64;
					returnValue[66]=executeUpdating(q65,con);
				}
				if(!oldValues[67].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_OHSR_SC_PARAM_TBL";
					String q66 = "UPDATE RWS_AST_OHSR_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 65;
					returnValue[67]=executeUpdating(q66,con);
				}
				if(!oldValues[68].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OHGLCI_HAB_LINK_TBL";
					String q67 = "UPDATE RWS_OHGLCI_HAB_LINK_TBL SET SUBCOMP_CODE='"+habCodeNew+"'||SUBSTR(SUBCOMP_CODE,17,24) where SUBSTR(SUBCOMP_CODE,1,16)='"+habCodeOld+"'";
					iter = 66;
					returnValue[68]=executeUpdating(q67,con);
				}
				if(!oldValues[69].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OHGLCI_HAB_LINK_TBL";
					String q68 = "UPDATE RWS_OHGLCI_HAB_LINK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 67;
					returnValue[69]=executeUpdating(q68,con);
				}
				if(!oldValues[70].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PWS_SP_HC_PC_SC_PARAM_TBL";
					String q69 = "UPDATE RWS_PWS_SP_HC_PC_SC_PARAM_TBL SET SPHCPCSC_CODE='"+habCodeNew+"'||SUBSTR(SPHCPCSC_CODE,17,24) where SUBSTR(SPHCPCSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 68;
					returnValue[70]=executeUpdating(q69,con);
				}
				if(!oldValues[71].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CW_COLLWELL_PARAM_TBL";
					String q70 = "UPDATE RWS_AST_CW_COLLWELL_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 69;
					returnValue[71]=executeUpdating(q70,con);
				}
				if(!oldValues[72].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CW_COLLWELL_PARAM_TBL";
					String q71 = "UPDATE RWS_AST_CW_COLLWELL_PARAM_TBL SET CW_COLLWELL_CODE='"+habCodeNew+"'||SUBSTR(CW_COLLWELL_CODE,17,24) where SUBSTR(CW_COLLWELL_CODE,1,16)='"+habCodeOld+"'";
					iter = 70;
					returnValue[72]=executeUpdating(q71,con);
				}
				if(!oldValues[73].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CP_SC_PARAM_TBL";
					String q72 = "UPDATE RWS_AST_CP_SC_PARAM_TBL SET CPSC_CODE='"+habCodeNew+"'||SUBSTR(CPSC_CODE,17,24) where SUBSTR(CPSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 71;
					returnValue[73]=executeUpdating(q72,con);
				}
				if(!oldValues[74].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CIS_SC_PARAM_TBL";
					String q73 = "UPDATE RWS_AST_CIS_SC_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 72;
					returnValue[74]=executeUpdating(q73,con);
				}
				if(!oldValues[75].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CIS_SC_PARAM_TBL";
					String q74 = "UPDATE RWS_AST_CIS_SC_PARAM_TBL SET CISSC_CODE='"+habCodeNew+"'||SUBSTR(CISSC_CODE,17,24) where SUBSTR(CISSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 73;
					returnValue[75]=executeUpdating(q74,con);
				}
				if(!oldValues[76].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CHLORINATION_TBL";
					String q75 = "UPDATE RWS_AST_CHLORINATION_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 74;
					returnValue[76]=executeUpdating(q75,con);
				}
				if(!oldValues[77].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_CHLORINATION_TBL";
					String q76 = "UPDATE RWS_AST_CHLORINATION_TBL SET CL_CODE='"+habCodeNew+"'||SUBSTR(CL_CODE,17,24) where SUBSTR(CL_CODE,1,16)='"+habCodeOld+"'";
					iter = 75;
					returnValue[77]=executeUpdating(q76,con);
				}
				if(!oldValues[78].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_BPT_PARAM_TBL";
					String q77 = "UPDATE RWS_AST_BPT_PARAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 76;
					returnValue[78]=executeUpdating(q77,con);
				}
				if(!oldValues[79].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DWTANK_MST_TBL";
					String q78 = "UPDATE RWS_DWTANK_MST_TBL SET POND_CODE='"+habCodeNew+"'||SUBSTR(POND_CODE,17,24) where SUBSTR(POND_CODE,1,16)='"+habCodeOld+"'";
					iter = 77;
					returnValue[79]=executeUpdating(q78,con);
				}
				if(!oldValues[80].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DWTANK_MST_TBL";
					String q79 = "UPDATE RWS_DWTANK_MST_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 78;
					returnValue[80]=executeUpdating(q79,con);
				}
				if(!oldValues[81].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OPEN_WELL_MAST_TBL";
					String q80 = "UPDATE RWS_OPEN_WELL_MAST_TBL SET OPENWELL_CODE ='"+habCodeNew+"'||SUBSTR(OPENWELL_CODE,17,24) where SUBSTR(OPENWELL_CODE,1,16)='"+habCodeOld+"'";
					iter = 79;
					returnValue[81]=executeUpdating(q80,con);
				}
				if(!oldValues[82].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OPEN_WELL_MAST_TBL";
					String q81 = "UPDATE RWS_OPEN_WELL_MAST_TBL SET HABITATION_CODE ='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 80;
					returnValue[82]=executeUpdating(q81,con);
				}
				if(!oldValues[83].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OPENWELL_POND_TBL";
					String q82 = "UPDATE RWS_OPENWELL_POND_TBL SET POND_CODE='"+habCodeNew+"'||SUBSTR(POND_CODE,17,24) where SUBSTR(POND_CODE,1,16)='"+habCodeOld+"'";
					iter = 81;
					returnValue[83]=executeUpdating(q82,con);
				}
				if(!oldValues[84].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OPENWELL_POND_TBL";
					String q83 = "UPDATE RWS_OPENWELL_POND_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 82;
					returnValue[84]=executeUpdating(q83,con);
				}		
				if(!oldValues[85].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_GRAVITYMAIN_PIPES_TBL";
					String q84 = "UPDATE RWS_GRAVITYMAIN_PIPES_TBL SET GM_CODE='"+habCodeNew+"'||SUBSTR(GM_CODE,17,24) where SUBSTR(GM_CODE,1,16)='"+habCodeOld+"'";
					iter = 83;
					returnValue[85]=executeUpdating(q84,con);
				}
				if(!oldValues[86].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HP_SUBCOMP_PARAM_TBL";
					String q85 = "UPDATE RWS_HP_SUBCOMP_PARAM_TBL SET HP_CODE='"+habCodeNew+"'||SUBSTR(HP_CODE,17,24) where SUBSTR(HP_CODE,1,16)='"+habCodeOld+"'";
					iter = 84;
					returnValue[86]=executeUpdating(q85,con);
				}
				if(!oldValues[87].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_HANDPUMPS_TBL";
					String q86 = "UPDATE RWS_HANDPUMPS_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 85;
					returnValue[87]=executeUpdating(q86,con);
				}
				if(!oldValues[88].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DISTRIBUTION_PIPES_TBL";
					String q87 = "UPDATE RWS_DISTRIBUTION_PIPES_TBL SET DISTRISC_CODE='"+habCodeNew+"'||SUBSTR(DISTRISC_CODE,17,24) where SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"'";
					iter = 86;
					returnValue[88]=executeUpdating(q87,con);
				}
				if(!oldValues[89].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PWS_DISTRIBUTION_PIPES_TBL";
					String q88 = "UPDATE RWS_PWS_DISTRIBUTION_PIPES_TBL SET DISTRISC_CODE='"+habCodeNew+"'||SUBSTR(DISTRISC_CODE,17,24) where SUBSTR(DISTRISC_CODE,1,16)='"+habCodeOld+"'";
					iter = 87;
					returnValue[89]=executeUpdating(q88,con);
				}
				if(!oldValues[90].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_GLSROHSROHBR_SC_PARAM_TBL";
					String q89 = "UPDATE RWS_GLSROHSROHBR_SC_PARAM_TBL SET SCHEME_CODE='"+habCodeNew+"'||SUBSTR(SCHEME_CODE,17,24)  where SUBSTR(SCHEME_CODE,1,16)='"+habCodeOld+"'";
					iter = 88;
					returnValue[90]=executeUpdating(q89,con);
				}
				if(!oldValues[91].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_WORK_ADMN_TBL";
					String q90 = "UPDATE RWS_WORK_ADMN_TBL SET LEAD_HABITATION='"+habCodeNew+"' where LEAD_HABITATION='"+habCodeOld+"'";
					iter = 89;
					returnValue[91]=executeUpdating(q90,con);
				}
				if(!oldValues[92].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ADMN_HAB_LNK_TBL";
					String q91 = "UPDATE RWS_ADMN_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 90;
					returnValue[92]=executeUpdating(q91,con);
				}
				if(!oldValues[93].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_REV_ADM_SANC_HAB_LNK_TBL";
					String q92 = "UPDATE RWS_REV_ADM_SANC_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 91;
					returnValue[93]=executeUpdating(q92,con);
				}
				if(!oldValues[94].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_NEW_REVISED_EST_TBL";
					String q93 = "UPDATE RWS_NEW_REVISED_EST_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 92;
					returnValue[94]=executeUpdating(q93,con);
				}
				if(!oldValues[95].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_EST_NEW_HAB_LNK_TBL";
					String q94 = "UPDATE RWS_EST_NEW_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 93;
					returnValue[95]=executeUpdating(q94,con);
				}
				if(!oldValues[96].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_REV_EST_NEW_HAB_LNK_TBL";
					String q95 = "UPDATE RWS_REV_EST_NEW_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 94;
					returnValue[96]=executeUpdating(q95,con);
				}
				if(!oldValues[97].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_IDEN_FIN_TBL";
					String q96 = "UPDATE RWS_SOURCE_IDEN_FIN_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 95;
					returnValue[97]=executeUpdating(q96,con);
				}
				if(!oldValues[98].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SOURCE_IDEN_FIN_TBL";
					String q97 = "UPDATE RWS_SOURCE_IDEN_FIN_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 96;
					returnValue[98]=executeUpdating(q97,con);
				}
				if(!oldValues[99].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_WORK_COMP_HAB_LNK_TBL";
					String q98 = "UPDATE RWS_WORK_COMP_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 97;
					returnValue[99]=executeUpdating(q98,con);
				}
				if(!oldValues[100].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PRAJAPADAM_EXIST_SCH_TBL";
					String q99 = "UPDATE RWS_PRAJAPADAM_EXIST_SCH_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 98;
					returnValue[100]=executeUpdating(q99,con);
				}
				if(!oldValues[101].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TEMP_PROPOSAL_HAB_TBL";
					String q100 = "UPDATE RWS_TEMP_PROPOSAL_HAB_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 99;
					returnValue[101]=executeUpdating(q100,con);
				}
				if(!oldValues[102].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TEMP_OM_PROPOSAL_HAB_TBL";
					String q101 = "UPDATE RWS_TEMP_OM_PROPOSAL_HAB_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 100;
					returnValue[102]=executeUpdating(q101,con);
				}
				if(!oldValues[103].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OM_PROPOSAL_HAB_LNK_TBL";
					String q102 = "UPDATE RWS_OM_PROPOSAL_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 101;
					returnValue[103]=executeUpdating(q102,con);
				}
				if(!oldValues[104].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DDWS_WORKS_MPR_TBL";
					String q103 = "UPDATE RWS_DDWS_WORKS_MPR_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 102;
					returnValue[104]=executeUpdating(q103,con);
				}
				if(!oldValues[105].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_REP_PROPOSAL_TBL";
					String q104 = "UPDATE RWS_REP_PROPOSAL_TBL SET LEAD_HAB_CODE='"+habCodeNew+"' where LEAD_HAB_CODE='"+habCodeOld+"'";
					iter = 103;
					returnValue[105]=executeUpdating(q104,con);
				}
				if(!oldValues[106].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PROPOSAL_HL_MIRROR_TBL";
					String q105 = "UPDATE RWS_PROPOSAL_HL_MIRROR_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 104;
					returnValue[106]=executeUpdating(q105,con);
				}
				if(!oldValues[107].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PROPOSAL_HAB_LNK_TBL";
					String q106 = "UPDATE RWS_PROPOSAL_HAB_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 105;
					returnValue[107]=executeUpdating(q106,con);
				}
				if(!oldValues[108].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PRAJAPADAM_TBL";
					String q107 = "UPDATE RWS_PRAJAPADAM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 106;
					returnValue[108]=executeUpdating(q107,con);
				}
				if(!oldValues[109].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SCHOOL_MASTER_TBL";
					String q108 = "UPDATE RWS_SCHOOL_MASTER_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 107;
					returnValue[109]=executeUpdating(q108,con);
				}
				if(!oldValues[110].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SCHOOL_ASSET_LNK_TBL";
					String q109 = "UPDATE RWS_SCHOOL_ASSET_LNK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 108;
					returnValue[110]=executeUpdating(q109,con);
				}
				if(!oldValues[111].equals("0"))
				{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DDWS_SCHOOLS_MPR_TBL";
					String q110 = "UPDATE RWS_DDWS_SCHOOLS_MPR_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 109;
					returnValue[111]=executeUpdating(q110,con);
				}
				if(!oldValues[112].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_WATER_SAMPLE_COLLECT_TBL";
					String q111 = "UPDATE RWS_WATER_SAMPLE_COLLECT_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 110;
					returnValue[112]=executeUpdating(q111,con);
				}
				if(!oldValues[113].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_WATER_SAMPLE_COLLECT_TBL";
					String q112 = "UPDATE RWS_WATER_SAMPLE_COLLECT_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 111;
					returnValue[113]=executeUpdating(q112,con);
				}
				if(!oldValues[114].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_WQ_TEST_RESULTS_TBL";
					String q113 = "UPDATE RWS_WQ_TEST_RESULTS_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 112;
					returnValue[114]=executeUpdating(q113,con);
				}
				if(!oldValues[115].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_FTK_TESTING_TBL";
					String q114 = "UPDATE RWS_FTK_TESTING_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where SUBSTR(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 113;
					returnValue[115]=executeUpdating(q114,con);
				}
				if(!oldValues[116].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_TBL";
					String q115 = "UPDATE RWS_DROUGHT_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 114;
					returnValue[116]=executeUpdating(q115,con);
				}
				if(!oldValues[117].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_EXIST_SCH_TBL";
					String q116 = "UPDATE RWS_DROUGHT_EXIST_SCH_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 115;		
					returnValue[117]=executeUpdating(q116,con);
				}
				if(!oldValues[118].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_AST_STANDPOST_TBL";
					qq = "UPDATE RWS_AST_STANDPOST_TBL SET STANDPOST_CODE='"+habCodeNew+"'||SUBSTR(STANDPOST_CODE,17,24) where substr(STANDPOST_CODE,1,16)='"+habCodeOld+"'";
					iter = 116;		
					returnValue[118]=executeUpdating(qq,con);
				}
				if(!oldValues[119].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_COMPONENT_IMAGE_TBL";
					qq = "UPDATE RWS_ASSET_COMPONENT_IMAGE_TBL SET ASSET_COMPONENT='"+habCodeNew+"'||SUBSTR(ASSET_COMPONENT,17,24) where substr(ASSET_COMPONENT,1,16)='"+habCodeOld+"'";
					iter = 117;		
					returnValue[119]=executeUpdating(qq,con);
				}
				if(!oldValues[120].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_ASSET_COMPONENT_REPAIR_TBL";
					qq = "UPDATE RWS_ASSET_COMPONENT_REPAIR_TBL SET ASSET_COMP_CODE='"+habCodeNew+"'||SUBSTR(ASSET_COMP_CODE,17,24) where substr(ASSET_COMP_CODE,1,16)='"+habCodeOld+"'";
					iter = 118;		
					returnValue[120]=executeUpdating(qq,con);
				}
				if(!oldValues[121].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_MOBILE_SMS_REGISTER_TBL";
					qq = "UPDATE RWS_MOBILE_SMS_REGISTER_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 119;		
					returnValue[121]=executeUpdating(qq,con);
				}				
				if(!oldValues[122].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TANKER_REG_TBL";
					qq = "UPDATE RWS_TANKER_REG_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 120;		
					returnValue[122]=executeUpdating(qq,con);
				}				
				if(!oldValues[123].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TANKER_SRC_DEST_DIS_TBL";
					qq = "UPDATE RWS_TANKER_SRC_DEST_DIS_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where substr(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 121;		
					returnValue[123]=executeUpdating(qq,con);
				}
				if(!oldValues[124].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TANKER_MOVEMENT_TBL";
					qq = "UPDATE RWS_TANKER_MOVEMENT_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where substr(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 122;		
					returnValue[124]=executeUpdating(qq,con);
				}
				if(!oldValues[125].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_TANKER_DEST_LOCATION_TBL";
					qq = "UPDATE RWS_TANKER_DEST_LOCATION_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 123;		
					returnValue[125]=executeUpdating(qq,con);
				}
				if(!oldValues[126].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DWTANK_MST_TBL";
					qq = "UPDATE RWS_DWTANK_MST_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 124;		
					returnValue[126]=executeUpdating(qq,con);
				}
				if(!oldValues[127].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DWTANK_MST_TBL";
					qq = "UPDATE RWS_DWTANK_MST_TBL SET POND_CODE='"+habCodeNew+"'||SUBSTR(POND_CODE,17,24) where substr(POND_CODE,1,16)='"+habCodeOld+"'";
					iter = 125;		
					returnValue[127]=executeUpdating(qq,con);
				}
				if(!oldValues[128].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_TANKER_SMS_TBL";
					qq = "UPDATE RWS_DROUGHT_TANKER_SMS_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 126;		
					returnValue[128]=executeUpdating(qq,con);
				}
				if(!oldValues[129].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_SSTANK_TBL";
					qq = "UPDATE RWS_DROUGHT_SSTANK_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 127;		
					returnValue[129]=executeUpdating(qq,con);
				}
				if(!oldValues[130].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_SSTANK_TBL";
					qq = "UPDATE RWS_DROUGHT_SSTANK_TBL SET SSSC_CODE='"+habCodeNew+"'||SUBSTR(SSSC_CODE,17,24) where substr(SSSC_CODE,1,16)='"+habCodeOld+"'";
					iter = 128;		
					returnValue[130]=executeUpdating(qq,con);
				}
				if(!oldValues[131].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SMS_IN_OUT_STATUS_TBL";
					qq = "UPDATE RWS_SMS_IN_OUT_STATUS_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 129;		
					returnValue[131]=executeUpdating(qq,con);
				}
				if(!oldValues[132].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_SCHEME_STATUS_SMS_TBL";
					qq = "UPDATE RWS_SCHEME_STATUS_SMS_TBL SET COMPONENT_CODE='"+habCodeNew+"'||SUBSTR(COMPONENT_CODE,17,24) where substr(COMPONENT_CODE,1,16)='"+habCodeOld+"'";
					iter = 130;		
					returnValue[132]=executeUpdating(qq,con);
				}
				if(!oldValues[133].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_RESIDUAL_CHLORINE_SMS_TBL";
					qq = "UPDATE RWS_RESIDUAL_CHLORINE_SMS_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where substr(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 131;		
					returnValue[133]=executeUpdating(qq,con);
				}
				if(!oldValues[134].equals("0")){
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_OHSR_GLSR_SMS_TBL";
					qq = "UPDATE RWS_OHSR_GLSR_SMS_TBL SET COMPONENT_CODE='"+habCodeNew+"'||SUBSTR(COMPONENT_CODE,17,24) where substr(COMPONENT_CODE,1,16)='"+habCodeOld+"'";
					iter = 132;		
					returnValue[134]=executeUpdating(qq,con);
				}				
				if(!oldValues[135].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_PUSHKAR_WORK_TBL";
					qq = "UPDATE RWS_PUSHKAR_WORK_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 133;		
					returnValue[135]=executeUpdating(qq,con);
				}
				if(!oldValues[136].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_GENERIC_COMPLAINTS_REG_TBL";
					qq = "UPDATE RWS_GENERIC_COMPLAINTS_REG_TBL SET HABITATION_CODE='"+habCodeNew+"' where HABITATION_CODE='"+habCodeOld+"'";
					iter = 134;		
					returnValue[136]=executeUpdating(qq,con);
				}
				if(!oldValues[137].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_COMPLAINTS_REGISTER_TBL";
					qq = "UPDATE RWS_COMPLAINTS_REGISTER_TBL SET SOURCE_CODE='"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24) where substr(SOURCE_CODE,1,16)='"+habCodeOld+"'";
					iter = 135;		
					returnValue[137]=executeUpdating(qq,con);
				}
				if(!oldValues[138].equals("0"))	{
					statusTracker = "ERROR OCCURED - UPDATION IN RWS_DROUGHT_NEWSPAPER_ITEM_TBL";
					qq = "UPDATE RWS_DROUGHT_NEWSPAPER_ITEM_TBL SET HAB_CODE='"+habCodeNew+"' where HAB_CODE='"+habCodeOld+"'";
					iter = 136;		
					returnValue[138]=executeUpdating(qq,con);
				}			
				
				statusTracker = "ERROR OCCURED - UPDATING THE FLAG IN MIRROR TABLE";
				String qfin = "update rws_master_data_conver_mir_tbl set Hab_flag = 'T'";
				executeUpdating(qfin,con);
				statusTracker = "Successfully Converted";
				int iter1 = iter;
				boolean flag = false;
				for(int k=iter1;k<=117;k++){
					if(oldValues[k].equals("0")){
						flag = true;
					}
					else{
						flag = false;
					}
				}
				if(flag){
					for(int k=iter1;k<=117;k++){
						iter++;
					}
				}
				
				if(statusTracker.equals("Successfully Converted")){
					con.commit();
					con.setAutoCommit(true);
					try{
						qq = "insert into RWS_NTR_SUJALA_MASTER_TBL  (HAB_CODE,SOURCE_CODE,TEST_ID,TEST_DATE,QUALITY_ISSUE,TYPE_OF_PLANT,HEALTH_ISSUES,BLDG_AVAILABLE,BLDG_NAME,BLDG_LOCATION,BLDG_SIZE,WATER_AVAILABLE,WATER_DISTANCE,POWER_SUPPLY,WATER_PLANT_EXTIST,WATER_PLANT_FIRM,WATER_PLANT_LOCATION,PLANT_EXIST_TYPE,PLANT_CAPACITY,TAKE_PROGRAMME_VOL,TAKE_PROGRAMME_VOL_NAME,TAKE_PROGRAMME_VOL_LOC,PHASE) "
								+ "( select '"+habCodeNew+"','"+habCodeNew+"'||SUBSTR(SOURCE_CODE,17,24),TEST_ID,TEST_DATE,QUALITY_ISSUE,TYPE_OF_PLANT,HEALTH_ISSUES,BLDG_AVAILABLE,BLDG_NAME,BLDG_LOCATION,BLDG_SIZE,WATER_AVAILABLE,WATER_DISTANCE,POWER_SUPPLY,WATER_PLANT_EXTIST,WATER_PLANT_FIRM,WATER_PLANT_LOCATION,PLANT_EXIST_TYPE,PLANT_CAPACITY,TAKE_PROGRAMME_VOL,TAKE_PROGRAMME_VOL_NAME,TAKE_PROGRAMME_VOL_LOC,PHASE from RWS_NTR_SUJALA_MASTER_TBL where HAB_CODE='"+habCodeOld+"')";
						executeUpdating(qq,con);

						qq = "insert into RWS_NTR_SUJALA_HAB_IMPL_TBL (HABITATION_CODE,IMPLEMENTATION_DT,PLANT_TYPE_INSTALLED,PLANT_CAPACITY,INSTALLATION_AGENCY_TYPE,INSTALLATION_AGENCY_NAME,MAINTENANCE_AGENCY_TYPE,MAINTENANCE_AGENCY_NAME,PREPARED_BY,UPDATE_DATE)"
								+ "(select '"+habCodeNew+"',IMPLEMENTATION_DT,PLANT_TYPE_INSTALLED,PLANT_CAPACITY,INSTALLATION_AGENCY_TYPE,INSTALLATION_AGENCY_NAME,MAINTENANCE_AGENCY_TYPE,MAINTENANCE_AGENCY_NAME,PREPARED_BY,UPDATE_DATE from RWS_NTR_SUJALA_HAB_IMPL_TBL where HABITATION_CODE='"+habCodeOld+"')";
						executeUpdating(qq,con);
					
						qq = "delete from RWS_NTR_SUJALA_HAB_IMPL_TBL where HABITATION_CODE='"+habCodeOld+"'";
						executeUpdating(qq,con);

						qq = "delete from RWS_NTR_SUJALA_MASTER_TBL where HAB_CODE='"+habCodeOld+"'";
						executeUpdating(qq,con);
					
					}
					catch(Exception e){
						System.out.println("The Exceptiion in HabConvertDao covertOldHabToNewHab :"+e.getMessage());
					}
				}
				else
					con.rollback();
			}
		}	
		catch(Exception e){
			e.printStackTrace();
			try {
				con.rollback();
			} catch (SQLException e1) {
				System.out.println("The Exceptiion in HabConvertDao covertOldHabToNewHab :"+e1.getMessage());
			}
		}
		returnList.add(0,statusTracker);
		returnList.add(1,returnValue);
		returnList.add(2,""+iter);
		return returnList;
	}
	
	public ResultSet getResultSet(String qry,Connection con) throws Exception {
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try	{
			stmt = con.prepareStatement(qry);
			rs = stmt.executeQuery();
		}
		catch(Exception e){
			System.out.println("The Exceptiion is in HabConvertDao getResultSet :"+e.getMessage());
		}

		return rs;
	}
	
	public int executeUpdating(String qry,Connection con) throws Exception{
		PreparedStatement stmt = null;
		int i = 0;
		stmt = con.prepareStatement(qry);
		i = stmt.executeUpdate();		
		return i;
	}
	
	public int executeUpdating1(String qry,Connection con) throws Exception {
		PreparedStatement stmt = null;
		int i = 0;
		try{
			stmt = con.prepareStatement(qry);
			i = stmt.executeUpdate();
		}
		catch(Exception e){
			System.out.println("The Exceptiion  is in HabConvertDao executeUpdating1 :"+e.getMessage());
		}		
		return i;
	}
	
	public static void closeResultSet(ResultSet rs){
		try {
				if(rs!=null){
					rs.close();
					rs = null;
				}
			} 
			catch (SQLException e){
				System.out.println("The Exceptiion is in HabConvertDao closeResultSet :"+e.getMessage());
		}
	}
	
	public static void closeStatement(Statement stmt)
	{
		try {
				if(stmt!=null)
				{
					stmt.close();
					stmt = null;
				}
			} 
			catch (SQLException e){
				System.out.println("The Exceptiion is in HabConvertDao closeStatement :"+e.getMessage());
		}
	}
	
	public static void closeConnection(Connection conn){
		try {
				if(conn!=null){
					conn.close();
					conn = null;
				}
			} 
			catch (SQLException e){
				System.out.println("The Exceptiion is in  HabConvertDao closeConnection :"+e.getMessage());
		}
	}
}