<%@ include file="/commons/rws_header1.jsp"%>
<%@ include file="/commons/rws_header2.jsp"%>
<!--<%@ page import="nic.watersoft.masters.RwsMasterData" %>-->
<%@ include file = "conn.jsp" %>
<%
	java.text.DateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
    java.util.Date currentDate = new java.util.Date();
    //System.out.println("printing currentdate1");
     System.out.println("current date is "+currentDate);
    String currentYear= dateFormat.format(currentDate).substring(0,4);
    java.util.Date d1 = dateFormat.parse(currentYear+"-03-31");
    System.out.println("d1 is "+d1);
    String financialYearFrom="";
    String financialYearTo="";
    if(currentDate.after(d1))
    {
    financialYearFrom="01-APR-"+currentYear;
    financialYearTo="31-Mar-"+(Integer.parseInt(currentYear)+1);
    }
    else
    {
    financialYearTo="01-APR-"+(Integer.parseInt(currentYear)-1);
    financialYearFrom="31-Mar-"+currentYear;
    System.out.println(financialYearFrom);
    System.out.println(financialYearTo);
    }
    
   
	//System.out.println("***********************REPORT BEGINING***********************");
	String rDistrict="", rConstituency="", rMandal="", rPanchayat="", rVillage="", rHabitation="", distvalue="", distname="", conname="", convalue="", manvalue="", manname="", panvalue="", panname="", vilvalue="", vilname ="";
	
	rDistrict = request.getParameter("district");
	//rMandal = request.getParameter("mandal");
	//rPanchayat = request.getParameter("panchayat");
	//rVillage = request.getParameter("village");
	//rHabitation=request.getParameter("habitation");
	rConstituency = request.getParameter("constituency");
	String query3="",query4="",query5="";
	//String districtName = (String)session.getAttribute("districtName");
	//String mandalName = (String)session.getAttribute("mandalName");
	//String panchayatName = (String)session.getAttribute("panchayatName");
	//String villageName = (String)session.getAttribute("villageName");
	//String constituencyName = (String)session.getAttribute("constituencyName");	
	//String habitationName = (String)session.getAttribute("habName");	
	
	String districtName="",mandalName="",panchayatName="",villageName="",constituencyName="",habitationName="";
	
	if(request.getParameter("distname")!=null)
	{
	districtName = request.getParameter("distname");
	session.setAttribute("districtName",districtName);
	}
	if(request.getParameter("manname")!=null)
	{
	mandalName = request.getParameter("manname");
	session.setAttribute("mandalName",mandalName);
	}
	if(request.getParameter("panname")!=null)
	{
	panchayatName = request.getParameter("panname");
	session.setAttribute("panchayatName",panchayatName);
	}
	if(request.getParameter("vilname")!=null)
	{
	villageName = request.getParameter("vilname");
	session.setAttribute("villageName",villageName);
	}
	if(request.getParameter("conname")!=null)
	{
	constituencyName = request.getParameter("conname");	
	session.setAttribute("constituencyName",constituencyName);
	}
	if(request.getParameter("habName")!=null)
	{
	habitationName = request.getParameter("habName");
	session.setAttribute("habName",habitationName);
	}	
	
	districtName = (String)session.getAttribute("districtName");
	//mandalName = (String)session.getAttribute("mandalName");
	//panchayatName = (String)session.getAttribute("panchayatName");
	//villageName = (String)session.getAttribute("villageName");
	constituencyName = (String)session.getAttribute("constituencyName");	
	//habitationName = (String)session.getAttribute("habName");	
	
	String query=null, query1 = null,query2=null;
	ResultSet rs1 = null;
	ResultSet rs2 = null;
	Statement stmt1 = null;
	PreparedStatement pstmt = null;
	int slno = 0,total=0;
	int i = 0;

	//int[] gcount = new int[8];
	//int[] gcount1= new int[8];
	//String[] coveragestatus = {"FC","NC","NSS","PC1","PC2","PC3","PC4","UI"};
try
{
%>
<html>
<head>
<!-- 
<script>
	window.history.forward(1);
</script>
 -->
</head>
<body bgcolor="#edf2f8">

<form name=f1 method="post">

<table border = 1 cellspacing = 0 cellpadding = 0 height=5% width="100%" bordercolor=#000000 style="border-collapse:collapse" bgcolor="#ffffff" align = "center">
	<caption>
		<table  border=0 rules=none style="border-collapse:collapse" align = "right">			
			<tr align="right">
			    <td class="bwborder"><a href="/pred/home.jsp?loginMode=watersoft">Home|</a></td>
				<td class="bwborder"><a href="./rws_worksmonitoring_progstatus_select.jsp">Back|</a></td>
				<!--<td class="bwborder"><a href="./constituency_excelrpt.jsp?district=<%=rDistrict%>&constituency=<%=rConstituency%>&mandal=<%=rMandal%>&panchayat=<%=rPanchayat%>&village=<%=rVillage%>" target="_new">Excel|</a></td>-->
				 
			</tr>
		</table>
	</caption>
<% 
	//stmt = conn.createStatement();
    //for district
    
    //CALCULATING CURRENT FINANCIAL YEAR
    
    
    //END OF CALCULATING CURRENT FINANCIAL YEAR
	if(rDistrict != null && rDistrict.equals("00"))
	{
			
	   query2 = " SELECT distinct A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR ,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC ,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE > '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END) AS A_NON_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.ADMIN_DATE >'"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN "+
				" A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,A.PROGRAMME_CODE AS  A_CODE,P.PROGRAMME_NAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL   "+
				" AL,RWS_PROGRAMME_TBL P WHERE A.WORK_ID=AL.WORK_ID AND P.PROGRAMME_CODE=A.PROGRAMME_CODE GROUP BY A.WORK_ID,A.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT A2.PROGRAMME_CODE AS A2_CODE,P.PROGRAMME_NAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL   AL2,RWS_PROGRAMME_TBL P WHERE A2.WORK_ID=AL2.WORK_ID  AND P.PROGRAMME_CODE=A2.PROGRAMME_CODE  GROUP BY A2.PROGRAMME_CODE,P.PROGRAMME_NAME) ,(SELECT A3.PROGRAMME_CODE AS A3_CODE,P.PROGRAMME_NAME AS A3_NAME,COUNT(DISTINCT(HAB_CODE)) AS A3_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A3,RWS_WORK_COMP_HAB_LNK_TBL AL3,RWS_PROGRAMME_TBL P WHERE A3.WORK_ID=AL3.WORK_ID  AND P.PROGRAMME_CODE=A3.PROGRAMME_CODE  GROUP BY A3.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST  "+
				" ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT  FROM RWS_REVISED_ADM_SANC_TBL RA1,"+
				" (SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,RA.PROGRAMME_CODE AS RA_CODE,P.PROGRAMME_NAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_PROGRAMME_TBL P WHERE RA.WORK_ID=RAL.WORK_ID   AND P.PROGRAMME_CODE=RA.PROGRAMME_CODE GROUP BY RA.WORK_ID,RA.PROGRAMME_CODE, P.PROGRAMME_NAME"+
				" ) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT   IS  NOT NULL THEN E1.SANCTIONED_AMOUNT   "+
				" ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM RWS_NEW_EST_TBL   E1,(SELECT E.WORK_ID AS  E_WORK_ID,SUBSTR(EL.WORK_ID,1,2) AS E_CODE,P.PROGRAMME_NAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL  "+
				" E,RWS_EST_NEW_HAB_LNK_TBL EL,RWS_PROGRAMME_TBL P WHERE E.WORK_ID=EL.WORK_ID  AND P.PROGRAMME_CODE=SUBSTR(EL.WORK_ID,1,2) GROUP BY E.WORK_ID,SUBSTR(EL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 "+
				" END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND DATE_OF_COMPLETION < SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND "+
				" AGREEMENT_DATE <SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,SUBSTR(AL.WORK_ID,1,2) AS CON_CODE,P.PROGRAMME_NAME  AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL "+
				" CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_PROGRAMME_TBL P WHERE CON.WORK_ID=AL.WORK_ID  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) GROUP BY CON.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME"+
				" )CON ,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION   IS NOT NULL AND DATE_OF_COMPLETION < SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN WC1.DATE_OF_COMM  IS  NOT NULL AND WC1.DATE_OF_COMM  <SYSDATE THEN 1 ELSE 0 END)AS "+
				" WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL   WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,SUBSTR(AL.WORK_ID,1,2) AS WC_CODE,P.PROGRAMME_NAME  AS WC_NAME FROM RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_DISTRICT_TBL D,RWS_PROGRAMME_TBL P WHERE "+
				" WC.WORK_ID=AL.WORK_ID  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) GROUP BY WC.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME"+
				" )WORKCOMP, (SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING  IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING FROM RWS_WORK_EXPENDITURE_TBL WE1,"+
				" (SELECT WE.WORK_ID AS  WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,SUBSTR(AL.WORK_ID,1,2) AS WE_CODE,P.PROGRAMME_NAME AS WE_NAME FROM  RWS_WORK_EXPENDITURE_TBL WE,RWS_ADMN_HAB_LNK_TBL AL,RWS_DISTRICT_TBL D,RWS_PROGRAMME_TBL P  WHERE WE.WORK_ID=AL.WORK_ID  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2)  GROUP BY WE.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME "+
				" )WHERE WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP, "+
				//code added
				"("+
				"select substr(expprev.work_id,1,2)AS expprev_prog,SUM(CASE WHEN EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR from RWS_WORK_EXP_UPTO_PRE_YEAR_TBL expprev  group by substr(expprev.work_id,1,2)"+
				")EXPPREV "+
				//end of code added
				"WHERE  expprev_prog(+)=SUBSTR(A1.WORK_ID,1,2) AND A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND A_CODE=A3_CODE(+) AND A_CODE=RA_CODE (+) AND A_CODE=E_CODE (+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT,A3_HAB_COUNT ,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED "+
				" ,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR ";


		System.out.println("first query2 is "+query2);
		stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
	}
	//for CONSTITUENCY
	if((rDistrict != null && !rDistrict.equals("00") && rConstituency.equals("-1")) || (rDistrict != null && !rDistrict.equals("00") && rConstituency.equals("00")))
	
	{
        //out.println("in condn 2");
		        query2="SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR ,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE > '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.ADMIN_DATE > '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN "+
				" A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,A.PROGRAMME_CODE AS  A_CODE,P.PROGRAMME_NAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL "+
				" AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A.WORK_ID=AL.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND P.PROGRAMME_CODE=A.PROGRAMME_CODE GROUP BY A.WORK_ID,A.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT A2.PROGRAMME_CODE AS A2_CODE,P.PROGRAMME_NAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL AL2,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A2.WORK_ID=AL2.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL2.HAB_CODE,1,2)  AND D.DIVISION_OFFICE_CODE=SUBSTR(A2.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=A2.PROGRAMME_CODE AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' GROUP BY A2.PROGRAMME_CODE,P.PROGRAMME_NAME"+
				" ),(SELECT A3.PROGRAMME_CODE AS A3_CODE,P.PROGRAMME_NAME AS A3_NAME,COUNT(DISTINCT(HAB_CODE)) AS A3_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A3,RWS_WORK_COMP_HAB_LNK_TBL AL3,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A3.WORK_ID=AL3.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL3.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A3.OFFICE_CODE,4,1) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"'  AND P.PROGRAMME_CODE=A3.PROGRAMME_CODE  GROUP BY A3.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST "+
				" ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT FROM RWS_REVISED_ADM_SANC_TBL RA1,"+
				"(SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,RA.PROGRAMME_CODE AS RA_CODE,P.PROGRAMME_NAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE RA.WORK_ID=RAL.WORK_ID  AND D.CIRCLE_OFFICE_CODE=SUBSTR(RAL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(RA.OFFICE_CODE,4,1) AND  P.PROGRAMME_CODE=RA.PROGRAMME_CODE AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' GROUP BY RA.WORK_ID,RA.PROGRAMME_CODE,P.PROGRAMME_NAME"+
				" ) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT IS NOT NULL THEN E1.SANCTIONED_AMOUNT "+
				" ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM RWS_NEW_EST_TBL   E1,(SELECT E.WORK_ID AS  E_WORK_ID,SUBSTR(EL.WORK_ID,1,2) AS E_CODE,P.PROGRAMME_NAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL "+
				" E,RWS_EST_NEW_HAB_LNK_TBL EL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE E.WORK_ID=EL.WORK_ID AND  D.CIRCLE_OFFICE_CODE=SUBSTR(EL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(E.OFFICE_CODE,4,1) AND  P.PROGRAMME_CODE=SUBSTR(EL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"'GROUP BY E.WORK_ID,SUBSTR(EL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 "+
				" END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND "+
				" TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,SUBSTR(AL.WORK_ID,1,2) AS CON_CODE,P.PROGRAMME_NAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL "+
				" CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE CON.WORK_ID=AL.WORK_ID  AND  AL.WORK_ID=A.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' GROUP BY CON.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME "+
				")CON,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN WC1.DATE_OF_COMM  IS  NOT NULL AND WC1.DATE_OF_COMM  <SYSDATE THEN 1   ELSE 0 END)AS "+
				" WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,SUBSTR(AL.WORK_ID,1,2) AS WC_CODE,P.PROGRAMME_NAME AS WC_NAME FROM RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE "+
				"  WC.WORK_ID=AL.WORK_ID AND  AL.WORK_ID=A.WORK_ID AND  D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' GROUP BY WC.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME"+
				" )WORKCOMP,(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING  IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING FROM RWS_WORK_EXPENDITURE_TBL WE1,"+
				"(SELECT WE.WORK_ID AS  WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,SUBSTR(AL.WORK_ID,1,2) AS WE_CODE,P.PROGRAMME_NAME AS WE_NAME FROM RWS_WORK_EXPENDITURE_TBL WE,RWS_ADMN_HAB_LNK_TBL  AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE WE.WORK_ID=AL.WORK_ID AND  AL.WORK_ID=A.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' GROUP BY WE.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" )WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP, "+
				//code added
				"("+
				"select substr(expprev.work_id,1,2)AS expprev_prog,SUM(CASE WHEN EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR from RWS_WORK_EXP_UPTO_PRE_YEAR_TBL expprev,RWS_WORK_ADMN_TBL WORKADMN where WORKADMN.WORK_ID=EXPPREV.WORK_ID and substr(expprev.work_id,5,2)='"+rDistrict+"' group by substr(expprev.work_id,1,2)"+
				")EXPPREV "+
				//end of code added
				" WHERE EXPPREV.expprev_prog(+)=substr(A_WORK_ID,1,2)  AND  A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND  A_CODE=A3_CODE(+) AND A_CODE=RA_CODE(+) AND A_CODE=E_CODE(+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED "+ ",CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR ";
				
		
       System.out.println("first query2 is "+query2);
	
     stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
	}
	
	//FOR MANDAL
	if(rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1"))
	{
		System.out.println("in mandal query");
		query2="SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR ,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE > '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE <= '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND  A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.ADMIN_DATE > '"+financialYearFrom+"' AND A1.ADMIN_DATE IS NOT NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN "+
				" A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,A.PROGRAMME_CODE AS  A_CODE,P.PROGRAMME_NAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL "+
				" AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A.WORK_ID=AL.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' AND P.PROGRAMME_CODE=A.PROGRAMME_CODE GROUP BY A.WORK_ID,A.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT A2.PROGRAMME_CODE AS A2_CODE,P.PROGRAMME_NAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL AL2,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A2.WORK_ID=AL2.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL2.HAB_CODE,1,2)  AND D.DIVISION_OFFICE_CODE=SUBSTR(A2.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=A2.PROGRAMME_CODE AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY A2.PROGRAMME_CODE,P.PROGRAMME_NAME"+
				" ),(SELECT A3.PROGRAMME_CODE AS A3_CODE,P.PROGRAMME_NAME AS A3_NAME,COUNT(DISTINCT(HAB_CODE)) AS A3_HAB_COUNT "+
				" FROM RWS_WORK_ADMN_TBL A3,RWS_WORK_COMP_HAB_LNK_TBL AL3,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE A3.WORK_ID=AL3.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL3.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A3.OFFICE_CODE,4,1) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' AND P.PROGRAMME_CODE=A3.PROGRAMME_CODE  GROUP BY A3.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST "+
				" ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT FROM RWS_REVISED_ADM_SANC_TBL RA1,"+
				"(SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,RA.PROGRAMME_CODE AS RA_CODE,P.PROGRAMME_NAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE RA.WORK_ID=RAL.WORK_ID  AND D.CIRCLE_OFFICE_CODE=SUBSTR(RAL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(RA.OFFICE_CODE,4,1) AND  P.PROGRAMME_CODE=RA.PROGRAMME_CODE AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY RA.WORK_ID,RA.PROGRAMME_CODE,P.PROGRAMME_NAME"+
				" ) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT IS NOT NULL THEN E1.SANCTIONED_AMOUNT "+
				" ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM RWS_NEW_EST_TBL   E1,(SELECT E.WORK_ID AS  E_WORK_ID,SUBSTR(EL.WORK_ID,1,2) AS E_CODE,P.PROGRAMME_NAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL "+
				" E,RWS_EST_NEW_HAB_LNK_TBL EL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P WHERE E.WORK_ID=EL.WORK_ID AND  D.CIRCLE_OFFICE_CODE=SUBSTR(EL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(E.OFFICE_CODE,4,1) AND  P.PROGRAMME_CODE=SUBSTR(EL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY E.WORK_ID,SUBSTR(EL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 "+
				" END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND "+
				" TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,SUBSTR(AL.WORK_ID,1,2) AS CON_CODE,P.PROGRAMME_NAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL "+
				" CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE CON.WORK_ID=AL.WORK_ID  AND  AL.WORK_ID=A.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY CON.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME "+
				")CON,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN WC1.DATE_OF_COMM  IS  NOT NULL AND WC1.DATE_OF_COMM  <SYSDATE THEN 1   ELSE 0 END)AS "+
				" WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,SUBSTR(AL.WORK_ID,1,2) AS WC_CODE,P.PROGRAMME_NAME AS WC_NAME FROM RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE "+
				"  WC.WORK_ID=AL.WORK_ID AND  AL.WORK_ID=A.WORK_ID AND  D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY WC.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME"+
				" )WORKCOMP,(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING  IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING FROM RWS_WORK_EXPENDITURE_TBL WE1,"+
				"(SELECT WE.WORK_ID AS  WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,SUBSTR(AL.WORK_ID,1,2) AS WE_CODE,P.PROGRAMME_NAME AS WE_NAME FROM RWS_WORK_EXPENDITURE_TBL WE,RWS_ADMN_HAB_LNK_TBL  AL,RWS_DIVISION_OFFICE_TBL D,RWS_PROGRAMME_TBL P,RWS_WORK_ADMN_TBL A WHERE WE.WORK_ID=AL.WORK_ID AND  AL.WORK_ID=A.WORK_ID AND D.CIRCLE_OFFICE_CODE=SUBSTR(AL.HAB_CODE,1,2) AND D.DIVISION_OFFICE_CODE=SUBSTR(A.OFFICE_CODE,4,1) AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND D.CIRCLE_OFFICE_CODE='"+rDistrict+"' AND D.DIVISION_OFFICE_CODE='"+rConstituency+"' GROUP BY WE.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" )WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP, "+ 
				//code added
				"("+
				"select substr(expprev.work_id,1,2)AS expprev_prog,SUM(CASE WHEN EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR from RWS_WORK_EXP_UPTO_PRE_YEAR_TBL expprev,RWS_WORK_ADMN_TBL WORKADMN where WORKADMN.WORK_ID=EXPPREV.WORK_ID and substr(expprev.work_id,5,2)='"+rDistrict+"' group by substr(expprev.work_id,1,2)"+
				")EXPPREV "+
				//end of code added
				" WHERE  EXPPREV.expprev_prog(+)=substr(A_WORK_ID,1,2) and  A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND  A_CODE=A3_CODE(+) AND A_CODE=RA_CODE(+) AND A_CODE=E_CODE(+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED "+ ",CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR";

				System.out.println("query is "+query2);
	  /*query2 = "SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,SUM(CASE WHEN A1.ADMIN_DATE < '01-APR-2007' THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE >= '01-APR-2007' THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN A1.ADMIN_DATE < '01-APR-2007' AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.ADMIN_DATE >= '01-APR-2007' AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,"+
				" (SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,A.PROGRAMME_CODE AS  A_CODE,P.PROGRAMME_NAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL   AL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE A.WORK_ID=AL.WORK_ID AND M.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=A.PROGRAMME_CODE AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(AL.HAB_CODE,6,2) GROUP BY A.WORK_ID,A.PROGRAMME_CODE,P.PROGRAMME_NAME) ,(SELECT A2.PROGRAMME_CODE AS A2_CODE,P.PROGRAMME_NAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT   FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL AL2,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE A2.WORK_ID=AL2.WORK_ID AND M.DCODE=SUBSTR(AL2.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=A2.PROGRAMME_CODE AND SUBSTR(AL2.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(AL2.HAB_CODE,6,2)  GROUP BY A2.PROGRAMME_CODE,P.PROGRAMME_NAME"+
				" )"+",(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST  ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT  FROM RWS_REVISED_ADM_SANC_TBL RA1,(SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,RA.PROGRAMME_CODE AS RA_CODE,P.PROGRAMME_NAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE RA.WORK_ID=RAL.WORK_ID  AND M.DCODE=SUBSTR(RAL.HAB_CODE,1,2) AND P.PROGRAMME_CODE=RA.PROGRAMME_CODE  AND SUBSTR(RAL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(RAL.HAB_CODE,6,2)  GROUP BY RA.WORK_ID,RA.PROGRAMME_CODE,P.PROGRAMME_NAME "+
				" ) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT   IS  NOT NULL THEN E1.SANCTIONED_AMOUNT   ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM RWS_NEW_EST_TBL   E1,(SELECT E.WORK_ID AS  E_WORK_ID,SUBSTR(EL.WORK_ID,1,2) AS E_CODE,P.PROGRAMME_NAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL  E,RWS_EST_NEW_HAB_LNK_TBL EL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE E.WORK_ID=EL.WORK_ID AND M.DCODE=SUBSTR(EL.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=SUBSTR(EL.WORK_ID,1,2) AND SUBSTR(EL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(EL.HAB_CODE,6,2)  GROUP BY E.WORK_ID,SUBSTR(EL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,SUBSTR(AL.WORK_ID,1,2) AS CON_CODE,P.PROGRAMME_NAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE CON.WORK_ID=AL.WORK_ID AND M.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(AL.HAB_CODE,6,2)  GROUP BY CON.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME)CON ,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION   IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN WC1.DATE_OF_COMM  IS  NOT NULL AND WC1.DATE_OF_COMM  <SYSDATE THEN 1   ELSE 0 END)AS WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL   WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,SUBSTR(AL.WORK_ID,1,2) AS WC_CODE,P.PROGRAMME_NAME AS WC_NAME FROM RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE WC.WORK_ID=AL.WORK_ID AND M.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(AL.HAB_CODE,6,2)  GROUP BY WC.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME)WORKCOMP"+",(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING  IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING,SUM(CASE WHEN WE1.EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  WE1.EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR   FROM RWS_WORK_EXPENDITURE_TBL WE1,"+
				"(SELECT WE.WORK_ID AS  WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,SUBSTR(AL.WORK_ID,1,2) AS WE_CODE,P.PROGRAMME_NAME AS WE_NAME FROM RWS_WORK_EXPENDITURE_TBL WE,RWS_ADMN_HAB_LNK_TBL  AL,RWS_MANDAL_TBL M,RWS_PROGRAMME_TBL P WHERE WE.WORK_ID=AL.WORK_ID AND M.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2) AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND M.DCODE='"+rDistrict+"' AND M.MCODE=SUBSTR(AL.HAB_CODE,6,2) GROUP BY WE.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				")WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP  WHERE A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND  A_CODE=A3_CODE(+) AND A_CODE=RA_CODE(+) AND A_CODE=E_CODE(+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT,A3_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED"+",CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR";*/

				
		//System.out.println("first query3 is "+query2);
		stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
	}
	
	//for panchayat
	/*if((rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1") && !rMandal.equals("-1") && !rMandal.equals("00") && rPanchayat.equals("-1")) || (rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1") && !rMandal.equals("-1") && !rMandal.equals("00") && !rPanchayat.equals("-1") && rPanchayat.equals("ALL") && rVillage.equals("-1")))
	{
	             query2="SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC ,SUM(CASE WHEN A1.SPILL_OVER ='Y' "+
				 " OR A1.SPILL_OVER ='y' THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.SPILL_OVER='N' OR A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN "+
				 " A1.SPILL_OVER ='Y' OR A1.SPILL_OVER='y' AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.SPILL_OVER='N' OR "+
				 " A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,P.PCODE AS  "+
				 " A_CODE,P.PNAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL AL,RWS_PANCHAYAT_TBL P WHERE A.WORK_ID=AL.WORK_ID AND P.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND "+
				 " SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"' AND P.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(AL.HAB_CODE,13,2) GROUP BY A.WORK_ID,P.PCODE,P.PNAME"+
				 " ) ,(SELECT P.PCODE AS A2_CODE,P.PNAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL   AL2,RWS_PANCHAYAT_TBL P WHERE "+
				 " A2.WORK_ID=AL2.WORK_ID  AND P.DCODE=SUBSTR(AL2.HAB_CODE,1,2)  AND SUBSTR(AL2.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  AND P.MCODE=SUBSTR(AL2.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(AL2.HAB_CODE,13,2)   GROUP BY P.PCODE,P.PNAME"+
				 " ) ,(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST  ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  "+
				 " RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT  FROM RWS_REVISED_ADM_SANC_TBL RA1,(SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,P.PCODE AS "+
				 " RA_CODE,P.PNAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_PANCHAYAT_TBL P WHERE RA.WORK_ID=RAL.WORK_ID   AND P.DCODE=SUBSTR(RAL.HAB_CODE,1,2)  AND SUBSTR(RAL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  "+
				 "  AND P.MCODE=SUBSTR(RAL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(RAL.HAB_CODE,13,2)   GROUP BY " +
				 " RA.WORK_ID,P.PCODE,P.PNAME) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS "+
				 " E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT   IS  NOT NULL THEN E1.SANCTIONED_AMOUNT   ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM "+
				 " RWS_NEW_EST_TBL   E1,(SELECT E.WORK_ID AS  E_WORK_ID,P.PCODE AS E_CODE,P.PNAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL  "+
				 " E,RWS_EST_NEW_HAB_LNK_TBL   EL,RWS_PANCHAYAT_TBL P WHERE E.WORK_ID=EL.WORK_ID  AND P.DCODE=SUBSTR(EL.HAB_CODE,1,2)  AND SUBSTR(EL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  "+
				 " AND P.MCODE=SUBSTR(EL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(EL.HAB_CODE,13,2)   GROUP BY E.WORK_ID,P.PCODE,P.PNAME"+
				 " ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 "+
				 " END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN "+
				 " DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND "+
				 " TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,"+
				 " (SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,P.PCODE AS CON_CODE,P.PNAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL "+
				 " CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_PANCHAYAT_TBL P WHERE CON.WORK_ID=AL.WORK_ID  AND P.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  "+
				 " AND P.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(AL.HAB_CODE,13,2)   GROUP BY CON.WORK_ID,P.PCODE,P.PNAME) WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME"+
				 " )CON ,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION   IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN "+
				 " WC1.COMMISION_DATE    IS  NOT NULL AND WC1.COMMISION_DATE <SYSDATE THEN 1   ELSE 0 END)AS WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL   WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,P.PCODE AS WC_CODE,P.PNAME AS WC_NAME FROM "+
				 " RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_PANCHAYAT_TBL P WHERE WC.WORK_ID=AL.WORK_ID  AND P.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  "+
				 " AND P.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(AL.HAB_CODE,13,2)  GROUP BY WC.WORK_ID,P.PCODE,P.PNAME) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME)WORKCOMP"+",(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING  IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING,SUM(CASE WHEN WE1.EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  WE1.EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR   FROM RWS_WORK_EXPENDITURE_TBL WE1,"+
				"(SELECT WE.WORK_ID AS  WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,P.PCODE AS WE_CODE,P.PNAME AS WE_NAME FROM RWS_WORK_EXPENDITURE_TBL WE,RWS_ADMN_HAB_LNK_TBL  AL,RWS_PANCHAYAT_TBL P WHERE WE.WORK_ID=AL.WORK_ID AND P.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND P.DCODE='"+rDistrict+"' AND P.MCODE='"+rMandal+"'  "+
				 " AND P.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND P.PCODE=SUBSTR(AL.HAB_CODE,13,2) GROUP BY WE.WORK_ID,P.PCODE,P.PNAME"+
				")WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP WHERE A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND A_CODE=RA_CODE(+) AND A_CODE=E_CODE "+
	 			 "(+) AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT ,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED ,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR";
             //System.out.println("first query2 aaa is "+query2);
           stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
		}
	
	//FOR VILLAGE 
	if(rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1") && !rMandal.equals("-1") && !rMandal.equals("00") && !rPanchayat.equals("ALL") && !rPanchayat.equals("-1") && rVillage.equals("-1") || (rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1") && !rMandal.equals("-1") && !rMandal.equals("00") && !rPanchayat.equals("ALL") && !rPanchayat.equals("-1") && !rVillage.equals("-1") && rVillage.equals("00")) )
	{
		
       query2 = " SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC ,SUM(CASE WHEN A1.SPILL_OVER ='Y' "+
				" OR A1.SPILL_OVER ='y' THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.SPILL_OVER='N' OR A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN "+
				" A1.SPILL_OVER ='Y' OR A1.SPILL_OVER='y' AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.SPILL_OVER='N' OR A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN "+
				" A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,V.VCODE AS  A_CODE,V.VNAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL   "+
				" AL,RWS_VILLAGE_TBL V WHERE A.WORK_ID=AL.WORK_ID AND V.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND "+
				" V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND V.PCODE=SUBSTR(AL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(AL.HAB_CODE,8,3) GROUP BY A.WORK_ID,V.VCODE,V.VNAME"+
				" ) ,(SELECT V.VCODE AS A2_CODE,V.VNAME AS A2_NAME,COUNT(DISTINCT(HAB_CODE)) AS A2_HAB_COUNT   FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL   AL2,RWS_VILLAGE_TBL V WHERE "+
				" A2.WORK_ID=AL2.WORK_ID  AND V.DCODE=SUBSTR(AL2.HAB_CODE,1,2)  AND SUBSTR(AL2.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(AL2.HAB_CODE,6,2)  AND "+
				" V.PCODE=SUBSTR(AL2.HAB_CODE,13,2) AND V.VCODE=SUBSTR(AL2.HAB_CODE,8,3)   GROUP BY V.VCODE,V.VNAME) ,(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST  "+
				" ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS RA_COUNT  FROM RWS_REVISED_ADM_SANC_TBL RA1,"+
				" (SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,V.VCODE AS RA_CODE,V.VNAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_VILLAGE_TBL V WHERE RA.WORK_ID=RAL.WORK_ID   "+
				" AND V.DCODE=SUBSTR(RAL.HAB_CODE,1,2)  AND SUBSTR(RAL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(RAL.HAB_CODE,6,2)  AND "+
				" V.PCODE=SUBSTR(RAL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(RAL.HAB_CODE,8,3)    GROUP BY RA.WORK_ID,V.VCODE,V.VNAME) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS "+
				" E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT   IS  NOT NULL THEN E1.SANCTIONED_AMOUNT   ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM RWS_NEW_EST_TBL   E1,"+
				" (SELECT E.WORK_ID AS  E_WORK_ID,V.VCODE AS E_CODE,V.VNAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL  E,RWS_EST_NEW_HAB_LNK_TBL   EL,RWS_VILLAGE_TBL V WHERE E.WORK_ID=EL.WORK_ID   AND V.DCODE=SUBSTR(EL.HAB_CODE,1,2)  "+
				" AND SUBSTR(EL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(EL.HAB_CODE,6,2)  AND V.PCODE=SUBSTR(EL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(EL.HAB_CODE,8,3)    GROUP BY E.WORK_ID,V.VCODE,V.VNAME"+
				" ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS "+
				" CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND "+
				" TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,V.VCODE AS "+
				" CON_CODE,V.VNAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_VILLAGE_TBL V WHERE CON.WORK_ID=AL.WORK_ID   AND V.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND "+
				" V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND V.PCODE=SUBSTR(AL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(AL.HAB_CODE,8,3)   GROUP BY CON.WORK_ID,V.VCODE,V.VNAME)"+
				" WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME)CON ,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION   IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN "+
				" WC1.COMMISION_DATE    IS  NOT NULL AND WC1.COMMISION_DATE <SYSDATE THEN 1   ELSE 0 END)AS WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL   WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,V.VCODE AS WC_CODE,V.VNAME AS WC_NAME FROM "+
				" RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_VILLAGE_TBL V WHERE WC.WORK_ID=AL.WORK_ID  AND V.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND "+
				" V.MCODE='"+rMandal+"'   AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND V.PCODE=SUBSTR(AL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(AL.HAB_CODE,8,3)   GROUP BY WC.WORK_ID,V.VCODE,V.VNAME"+
				" ) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME)WORKCOMP"+",(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING,SUM(CASE WHEN WE1.EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  WE1.EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR FROM RWS_WORK_EXPENDITURE_TBL WE1,(SELECT WE.WORK_ID AS WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,V.VCODE AS WE_CODE,V.VNAME AS WE_NAME FROM "+
				" RWS_WORK_EXPENDITURE_TBL  WE,RWS_ADMN_HAB_LNK_TBL   AL,RWS_VILLAGE_TBL V WHERE WE.WORK_ID=AL.WORK_ID  AND V.DCODE=SUBSTR(AL.HAB_CODE,1,2)  AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND V.DCODE='"+rDistrict+"' AND "+
				" V.MCODE='"+rMandal+"' AND V.PCODE='"+rPanchayat+"' AND V.MCODE=SUBSTR(AL.HAB_CODE,6,2)  AND V.PCODE=SUBSTR(AL.HAB_CODE,13,2) AND V.VCODE=SUBSTR(AL.HAB_CODE,8,3)   GROUP BY WE.WORK_ID,V.VCODE,V.VNAME"+
				")WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP WHERE A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND A_CODE=RA_CODE (+) AND A_CODE=E_CODE (+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT "+
				" ,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED ,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR";
				
				
		//System.out.println("first query2 is "+query2);
		stmt1 =conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
		
	}*/
	/*&& !rPanchayat.equals("ALL") && !rPanchayat.equals("-1") && !rVillage.equals("-1") && !rVillage.equals("00")*/
	//FOR HABITATION
	/*if(rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("00") && !rConstituency.equals("-1"))
	{
		

		query2= " SELECT A_CODE,A_NAME,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR,CON_AGMT_ENT,CON_TENDERED,CON_COMPLETED,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,A2_HAB_COUNT,RA_SANCTION_AMOUNT,E_NO_SANC ,SUM(CASE WHEN A1.SPILL_OVER ='Y' "+
				" OR A1.SPILL_OVER ='y' THEN 1 ELSE 0 END) AS A_SPILL_OVER,SUM(CASE WHEN A1.SPILL_OVER='N' OR A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL THEN 1 ELSE 0 END)AS A_NON_SPILL_OVER,SUM(CASE WHEN "+
				" A1.SPILL_OVER ='Y' OR A1.SPILL_OVER='y' AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_SPILL_OVER_AMT,SUM(CASE WHEN A1.SPILL_OVER='N' OR "+
				" A1.SPILL_OVER='n' OR A1.SPILL_OVER IS NULL AND A1.SANCTION_AMOUNT IS NOT NULL THEN A1.SANCTION_AMOUNT ELSE 0 END) AS A_NON_SPILL_OVER_AMT FROM RWS_WORK_ADMN_TBL A1,(SELECT A.WORK_ID AS A_WORK_ID,COUNT(distinct(A.WORK_ID)) AS A_COUNT,A.PROGRAMME_CODE AS  "+
				" A_CODE,P.PROGRAMME_NAME AS A_NAME FROM RWS_WORK_ADMN_TBL A,RWS_ADMN_HAB_LNK_TBL AL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE A.WORK_ID=AL.WORK_ID AND SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'"+
				" AND PR.PANCH_CODE=AL.HAB_CODE AND P.PROGRAMME_CODE=A.PROGRAMME_CODE GROUP BY A.WORK_ID,A.PROGRAMME_CODE,P.PROGRAMME_NAME) ,(SELECT A2.PROGRAMME_CODE AS A2_CODE,P.PROGRAMME_NAME AS A2_NAME,COUNT(DISTINCT(AL2.HAB_CODE)) AS A2_HAB_COUNT   "+
				" FROM RWS_WORK_ADMN_TBL A2,RWS_ADMN_HAB_LNK_TBL AL2,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE A2.WORK_ID=AL2.WORK_ID AND SUBSTR(AL2.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'"+
				" AND PR.PANCH_CODE=AL2.HAB_CODE AND P.PROGRAMME_CODE=A2.PROGRAMME_CODE GROUP BY A2.PROGRAMME_CODE,P.PROGRAMME_NAME),(SELECT RA_CODE,RA_NAME,SUM(CASE WHEN RA1.ESTIMATE_COST IS NOT NULL THEN RA1.ESTIMATE_COST  "+
				" ELSE 0 END)AS RA_ESTIMATE_AMOUNT,SUM(CASE WHEN RA1.REV_SANCTION_AMOUNT IS NOT NULL THEN  RA1.REV_SANCTION_AMOUNT ELSE 0 END)AS RA_SANCTION_AMOUNT,COUNT(DISTINCT(RA1.WORK_ID))AS "+
				" RA_COUNT  FROM RWS_REVISED_ADM_SANC_TBL RA1,(SELECT RA.WORK_ID AS  RA_WORK_ID,COUNT(distinct(RA.WORK_ID))AS RA_COUNT,RA.PROGRAMME_CODE AS RA_CODE,P.PROGRAMME_NAME AS RA_NAME FROM RWS_REVISED_ADM_SANC_TBL  "+
				" RA,RWS_REV_ADM_SANC_HAB_LNK_TBL RAL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE RA.WORK_ID=RAL.WORK_ID  AND SUBSTR(RAL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'   "+
				"  AND PR.PANCH_CODE=RAL.HAB_CODE AND P.PROGRAMME_CODE=RA.PROGRAMME_CODE GROUP BY RA.WORK_ID,RA.PROGRAMME_CODE,P.PROGRAMME_NAME) WHERE  RA1.WORK_ID=RA_WORK_ID GROUP BY RA_CODE,RA_NAME"+
				" ),(SELECT E_CODE,E_NAME,SUM(CASE WHEN E1.TS_NO  IS NOT NULL THEN  1 ELSE 0 END)AS E_NO_SANC,SUM(CASE WHEN E1.SANCTIONED_AMOUNT   IS  NOT NULL THEN E1.SANCTIONED_AMOUNT ELSE 0 END)AS E_SANCTION_AMOUNT,COUNT(distinct(E1.WORK_ID))AS  E_COUNT FROM "+
				" RWS_NEW_EST_TBL E1,(SELECT E.WORK_ID AS  E_WORK_ID,SUBSTR(EL.WORK_ID,1,2) AS E_CODE,P.PROGRAMME_NAME AS E_NAME,COUNT(distinct(E.WORK_ID))AS E_COUNT FROM RWS_NEW_EST_TBL  E,RWS_EST_NEW_HAB_LNK_TBL   EL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE E.WORK_ID=EL.WORK_ID   AND "+
				" SUBSTR(EL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'  AND PR.PANCH_CODE=EL.HAB_CODE AND P.PROGRAMME_CODE=SUBSTR(EL.WORK_ID,1,2) GROUP BY E.WORK_ID,SUBSTR(EL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  E1.WORK_ID=E_WORK_ID GROUP BY E_CODE,E_NAME)EST,(SELECT CON_CODE,CON_NAME,SUM(CASE WHEN CON1.AGREEMENT_DATE IS NOT NULL THEN 1  ELSE 0 END)AS CON_AGMT_ENT,SUM(CASE WHEN CON1.WORK_ID  IS NOT NULL THEN  1 ELSE 0 END)AS CON_TENDERED,COUNT(DISTINCT(CON1.WORK_ID))AS CON_COUNT ,SUM(CASE WHEN "+
				" DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(DATE_OF_COMPLETION,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_COMPLETED,SUM(CASE WHEN DATE_OF_COMPLETION IS NOT NULL AND TO_CHAR(AGREEMENT_DATE ,'DD-MON-YY')<SYSDATE THEN 1 ELSE 0 END)AS CON_GROUNDED  FROM "+
				" RWS_CONTRACTOR_SELECTION_TBL CON1,(SELECT CON.WORK_ID AS  CON_WORK_ID,COUNT(distinct(CON.WORK_ID))AS CON_COUNT,SUBSTR(AL.WORK_ID,1,2) AS CON_CODE,P.PROGRAMME_NAME AS CON_NAME FROM RWS_CONTRACTOR_SELECTION_TBL CON,RWS_ADMN_HAB_LNK_TBL AL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE CON.WORK_ID=AL.WORK_ID   AND "+
				" SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'  AND PR.PANCH_CODE=AL.HAB_CODE AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2)  GROUP BY CON.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME"+
				" ) WHERE  CON1.WORK_ID=CON_WORK_ID GROUP BY CON_CODE,CON_NAME)CON ,(SELECT WC_CODE,WC_NAME,SUM(CASE WHEN WC1.DATE_OF_COMPLETION   IS NOT NULL AND DATE_OF_COMPLETION <SYSDATE THEN  1 ELSE 0 END)AS WC_COMPLETED,SUM(CASE WHEN WC1.DATE_OF_COMM     IS  NOT NULL AND WC1.DATE_OF_COMM  <SYSDATE THEN 1   ELSE 0 END)AS "+
				" WC_COMMISSIONED FROM RWS_WORK_COMPLETION_TBL   WC1,(SELECT WC.WORK_ID AS  WC_WORK_ID,SUBSTR(AL.WORK_ID,1,2) AS WC_CODE,P.PROGRAMME_NAME AS WC_NAME FROM RWS_WORK_COMPLETION_TBL  WC,RWS_ADMN_HAB_LNK_TBL   AL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE WC.WORK_ID=AL.WORK_ID AND "+
				" SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'  AND PR.PANCH_CODE=AL.HAB_CODE AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2)  GROUP BY "+
				" WC.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  WC1.WORK_ID=WC_WORK_ID GROUP BY WC_CODE,WC_NAME)WORKCOMP"+",(SELECT WE_CODE,WE_NAME,SUM(CASE WHEN WE1.EXPENDITURE_UPTO IS NOT NULL THEN WE1.EXPENDITURE_UPTO  ELSE 0 END)AS WE_EXPENDITURE_UPTO,SUM(CASE WHEN WE1.EXPENDITURE_DURING IS NOT NULL THEN  WE1.EXPENDITURE_DURING  ELSE 0 END)AS WE_EXPENDITURE_DURING,SUM(CASE WHEN WE1.EXPENDITURE_UPTO_THE_PRE_YEAR IS NOT NULL THEN  WE1.EXPENDITURE_UPTO_THE_PRE_YEAR ELSE 0 END)AS WE_EXPENDITURE_PRE_YEAR FROM RWS_WORK_EXPENDITURE_TBL WE1,(SELECT WE.WORK_ID AS WE_WORK_ID,COUNT(distinct(WE.WORK_ID))AS WE_COUNT,SUBSTR(AL.WORK_ID,1,2) AS WE_CODE,P.PROGRAMME_NAME AS WE_NAME FROM RWS_WORK_EXPENDITURE_TBL  WE,RWS_ADMN_HAB_LNK_TBL AL,RWS_PANCHAYAT_RAJ_TBL PR,RWS_PROGRAMME_TBL P WHERE WE.WORK_ID=AL.WORK_ID AND "+
				" SUBSTR(AL.HAB_CODE,3,3)='"+rConstituency+"' AND SUBSTR(PR.PANCH_CODE,1,2)='"+rDistrict+"' AND SUBSTR(PR.PANCH_CODE,6,2)='"+rMandal+"'  AND PR.PANCH_CODE=AL.HAB_CODE AND P.PROGRAMME_CODE=SUBSTR(AL.WORK_ID,1,2)  GROUP BY "+
				" WE.WORK_ID,SUBSTR(AL.WORK_ID,1,2),P.PROGRAMME_NAME) WHERE  WE1.WORK_ID=WE_WORK_ID GROUP BY WE_CODE,WE_NAME)WORKEXP WHERE A1.WORK_ID=A_WORK_ID AND A_CODE=A2_CODE AND A_CODE=RA_CODE (+) AND A_CODE=E_CODE (+)  AND A_CODE=CON_CODE(+) AND A_CODE=WC_CODE(+) AND   A_CODE=WE_CODE(+) GROUP BY A_CODE,A_NAME,A2_HAB_COUNT "+
				" ,RA_SANCTION_AMOUNT,E_NO_SANC,CON_AGMT_ENT,CON_TENDERED ,CON_COMPLETED ,CON_GROUNDED,WC_COMPLETED,WC_COMMISSIONED,WE_EXPENDITURE_UPTO,WE_EXPENDITURE_DURING,WE_EXPENDITURE_PRE_YEAR";
		//System.out.println("first query2 is "+query2);
		stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
		
	}*/
	//rs = stmt.executeQuery(query);
	//System.out.println("query2 is "+query2);
	rs2 = stmt1.executeQuery(query2);
%>
<%@ include file="./rws_worksmonitoring_progstatus_label.jsp"%>
<%	
	float spillamt=0,nonspillamt=0,totalspillamt=0,totRevisedSanctionAmt=0;
	float expprev=0,expupto=0,expdur=0,cumexp=0,totexp=0;
	int spillover=0,nonspillover=0,totalspills=0,habsanction=0,tsanc=0,conten=0,conagmt=0,congr=0,concom=0,concomm=0,concount=0;
	String code="",name="";
	while(rs2.next())
	{
		
		
		
		++ slno;
	
%>
		<td class=rptValue><%=slno%></td>
		<%	if(rDistrict != null && rDistrict.equals("00") && rConstituency.equals("-1"))
		{		
%>		
		<td class=rptValue><a href="./rws_worksmonitoring_progstatus1_drill.jsp?progvalue=<%=rs2.getString(1)%>&progname=<%=rs2.getString("A_NAME")%>&distname=<%=districtName%>&district=<%=rDistrict%>&mandal=<%=rMandal%>&constituency=<%=rConstituency%>"><%=rs2.getString("A_NAME")%>
		</a></td>
<%
		}
		
	if(rDistrict != null && !rDistrict.equals("00") && rConstituency.equals("00")) 
		{	
			
%>		
		<td class=rptValue><a href="./rws_worksmonitoring_progstatus1_drill.jsp?district=<%=rDistrict%>&distname=<%=districtName%>&progvalue=<%=rs2.getString("A_CODE")%>&progname=<%=rs2.getString("A_NAME")%>&constituency=<%=rConstituency%>"><%=rs2.getString("A_NAME")%></a></td>
<%
		}
		
	if(rDistrict != null && !rDistrict.equals("00") && !rConstituency.equals("-1") && !rConstituency.equals("00"))
		{			
%>		
		<td class=rptValue><a href="./rws_worksmonitoring_progstatus1_drill.jsp?district=<%=rDistrict%>&distname=<%=districtName%>&constituency=<%=rConstituency%>&conname=<%=constituencyName%>&progvalue=<%=rs2.getString("A_CODE")%>&progname=<%=rs2.getString("A_NAME")%>"><%=rs2.getString("A_NAME")%></a></td>
<%
		}
		
 //System.out.println("1"); %>
			<td class=rptValue align="right"><%=rs2.getInt("A_SPILL_OVER")%></td>
		<% spillover=spillover+rs2.getInt("A_SPILL_OVER");
	 
 //System.out.println("2"); %>
			<td class=rptValue align="right"><%=rs2.getInt("A_NON_SPILL_OVER")%></td>
		<%
	 nonspillover=nonspillover+rs2.getInt("A_NON_SPILL_OVER");
 //System.out.println("3"); %>
			<td class=rptValue align="right"><%=rs2.getInt("A_SPILL_OVER")+rs2.getInt("A_NON_SPILL_OVER")%></td>
		<%
	 totalspills=totalspills+rs2.getInt("A_SPILL_OVER")+rs2.getInt("A_NON_SPILL_OVER");
 //System.out.println("4");
    spillamt=spillamt+rs2.getFloat("A_SPILL_OVER_AMT");
 %>
			<td class=rptValue align="right"><%=rs2.getFloat("A_SPILL_OVER_AMT")%></td>
		<%
	 nonspillamt=nonspillamt+rs2.getFloat("A_NON_SPILL_OVER_AMT");
 //System.out.println("5"); %>
			<td class=rptValue align="right"><%=rs2.getFloat("A_NON_SPILL_OVER_AMT")%></td>	
		<%
	  totalspillamt=totalspillamt+rs2.getFloat("A_SPILL_OVER_AMT")+rs2.getFloat("A_NON_SPILL_OVER_AMT");
 //System.out.println("6"); %>
			<td class=rptValue align="right"><%=rs2.getFloat("A_SPILL_OVER_AMT")+rs2.getFloat("A_NON_SPILL_OVER_AMT")%></td>		
				
		<%totRevisedSanctionAmt=totRevisedSanctionAmt+rs2.getFloat("RA_SANCTION_AMOUNT"); %>
			<td class=rptValue align="right"><%=rs2.getFloat("RA_SANCTION_AMOUNT")%></td>
		<%habsanction=habsanction+rs2.getInt("A2_HAB_COUNT"); %>
			<td class=rptValue align="right"><%=rs2.getInt("A2_HAB_COUNT")%></td>
		<%
			expprev=expprev+rs2.getFloat("WE_EXPENDITURE_PRE_YEAR");
		expupto=expupto+rs2.getFloat("WE_EXPENDITURE_UPTO");
		expdur=expdur+rs2.getFloat("WE_EXPENDITURE_DURING");
		 %>
			<td class=rptValue align="right"><%=rs2.getFloat("WE_EXPENDITURE_PRE_YEAR")%></td>
		<%cumexp=cumexp+rs2.getFloat("WE_EXPENDITURE_UPTO")+rs2.getFloat("WE_EXPENDITURE_DURING");
		totexp=totexp+rs2.getFloat("WE_EXPENDITURE_PRE_YEAR")+rs2.getFloat("WE_EXPENDITURE_UPTO")+
		rs2.getFloat("WE_EXPENDITURE_DURING"); %>
			<td class=rptValue align="right"><%=rs2.getFloat("WE_EXPENDITURE_UPTO")%></td>
		<%//System.out.println("11"); %>
			<td class=rptValue align="right"><%=rs2.getFloat("WE_EXPENDITURE_DURING")%></td>
		<%//System.out.println("12"); %>
		<td class=rptValue align="right"><%=rs2.getFloat("WE_EXPENDITURE_UPTO")+rs2.getFloat("WE_EXPENDITURE_DURING")%></td>
		<%//System.out.println("13"); %>
		<td class=rptValue align="right"><%=rs2.getFloat("WE_EXPENDITURE_PRE_YEAR")+rs2.getFloat("WE_EXPENDITURE_UPTO")+rs2.getFloat("WE_EXPENDITURE_DURING")%></td> 
		<%tsanc=tsanc+rs2.getInt("E_NO_SANC");
		    conten=conten+rs2.getInt("CON_TENDERED");
			conagmt=conagmt+rs2.getInt("CON_AGMT_ENT");
			congr=congr+rs2.getInt("CON_GROUNDED");
		    concom=concom+rs2.getInt("WC_COMPLETED");
			concomm=concomm+rs2.getInt("WC_COMMISSIONED");
			concount=concount+rs2.getInt("A3_HAB_COUNT");%>
		<td class=rptValue align="right"><%=rs2.getInt("E_NO_SANC")%></td>
		<%//System.out.println("15"); %>
			<td class=rptValue align="right"><%=rs2.getInt("CON_TENDERED")%></td>
		<%//System.out.println("16"); %>
			<td class=rptValue align="right"><%=rs2.getInt("CON_AGMT_ENT")%></td>
		<%//System.out.println("17"); %>
			<td class=rptValue align="right"><%=rs2.getInt("CON_GROUNDED")%></td>
		<%//System.out.println("18"); %>
			<td class=rptValue align="right"><%=rs2.getInt("WC_COMPLETED")%></td>
		<%//System.out.println("19"); %>
			<td class=rptValue align="right"><%=rs2.getInt("WC_COMMISSIONED")%></td>
		<%//System.out.println("20"); %>
			<td class=rptValue align="right"><%=rs2.getInt("A3_HAB_COUNT")%></td>
		</tr>

           
		<%	}%>
		<tr class="btext">
			 <td class=btext colspan=2>GrandTotal</td>
			  <td class=btext align="right" ><%=spillover%></td>
			  <td class=btext align="right"><%=nonspillover%></td>
               <td class=btext align="right"><%=totalspills%></td>
			   <td class=btext align="right"><%=Math.round(spillamt*100)/100f%></td>
			   <td class=btext align="right"><%=Math.round(nonspillamt*100)/100f%></td>
			   <td class=btext align="right"><%=Math.round(totalspillamt*100)/100f%></td>
			   <td class=btext align="right"><%=Math.round(totRevisedSanctionAmt*100)/100f%></td>
			  <td class=btext align="right"><%=habsanction%></td>
			    <td class=btext align="right"><%=Math.round(expprev*100)/100f%></td>
				<td class=btext align="right"><%=Math.round(expupto*100)/100f%></td>
				<td class=btext align="right"><%=Math.round(expdur*100)/100f%></td>
				<td class=btext align="right"><%=Math.round(cumexp*100)/100f%></td>
				<td class=btext align="right"><%=Math.round(totexp*100)/100f%></td>
				<td class=btext align="right"><%=tsanc%></td>
				<td class=btext align="right"><%=conten%></td>
				<td class=btext align="right"><%=conagmt%></td>
				<td class=btext align="right"><%=congr%></td>
				<td class=btext align="right"><%=concom%></td>
				<td class=btext align="right"><%=concomm%></td>
				<td class=btext align="right"><%=concount%></td>
			 </tr>
	<%	if(slno==0){%><tr><td class="rptValue" colspan="25" align="center"><a href="./rws_worksmonitoring_progstatus_select.jsp"><b>No Records</b></a></td></tr><%} 
			rs2.close();
			%>
</tr>
</table>
<%
		
}
	
catch(Exception e)
{
	//System.out.println("Exception in drill is "+e);
	e.printStackTrace();
}
finally
{

	if(conn!=null)
	conn.close();
}
%>

</form>
</body>
</html>
